const app=document.getElementById('app'),list=document.getElementById('messages'),input=document.getElementById('input'),toast=document.getElementById('toast');
const moreBtn=document.getElementById('moreBtn'),morePopover=document.getElementById('morePopover');
const modelBtn=document.getElementById('modelBtn'),modelPopover=document.getElementById('modelPopover'),modelBody=document.getElementById('modelBody'),modelBack=document.getElementById('modelBack'),modelClose=document.getElementById('modelClose'),modelBtnText=document.getElementById('modelBtnText'),thinkingSwitch=document.getElementById('thinkingSwitch');
const settingsBtn=document.getElementById('settingsBtn'),settingsPopover=document.getElementById('settingsPopover');
const drawerBtn=document.getElementById('drawerBtn'),drawerLayer=document.getElementById('drawerLayer'),drawerDim=document.getElementById('drawerDim'),sideDrawer=document.getElementById('sideDrawer'),drawerBack=document.getElementById('drawerBack');
const drawerTime=document.getElementById('drawerTime'),drawerDate=document.getElementById('drawerDate'),drawerTogetherDays=document.getElementById('drawerTogetherDays'),drawerTogetherDayCaption=document.getElementById('drawerTogetherDayCaption'),annivTrigger=document.getElementById('annivTrigger'),annivPicker=document.getElementById('annivPicker'),pickerDateText=document.getElementById('pickerDateText'),drawerTodoList=document.getElementById('drawerTodoList');
const MAIN_MODELS=[{id:'claude-fable-5',name:'Fable 5',desc:'For your toughest challenges'},{id:'claude-opus-5',name:'Opus 5',desc:''},{id:'claude-opus-4-6',name:'Opus 4.6',desc:''},{id:'claude-sonnet-4-6',name:'Sonnet 4.6',desc:''}];
const MORE_MODELS=[{id:'claude-sonnet-5',name:'Sonnet 5'},{id:'claude-haiku-4-5-20251001',name:'Haiku 4.5'},{id:'claude-opus-4-8',name:'Opus 4.8'},{id:'claude-opus-4-7',name:'Opus 4.7'}];
const LONG_MODELS=[{id:'claude-opus-4-6[1m]',name:'Opus 4.6 · 1M'},{id:'claude-opus-4-8[1m]',name:'Opus 4.8 · 1M'},{id:'claude-sonnet-5[1m]',name:'Sonnet 5 · 1M'}];
const EFFORTS=[{id:'low',name:'Low',desc:'Quick replies to simple questions'},{id:'medium',name:'Medium',desc:'Light, casual tasks'},{id:'high',name:'High',desc:'Balanced for everyday work'},{id:'xhigh',name:'Extra',desc:'Complex, detailed work'},{id:'max',name:'Max',desc:'The hardest problems. Takes longest.'}];
let currentModel='claude-opus-4-6',currentEffort='high',modelView='main',thinkingOn=true;
document.querySelectorAll('.sheep').forEach(btn=>btn.onclick=()=>{const d=btn.closest('.msg').querySelector('.details'),open=d.classList.toggle('open');btn.setAttribute('aria-expanded',open)});
function hint(text='这里只是前端预览'){toast.textContent=text;toast.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>toast.classList.remove('show'),1400)}
function resizeInput(){input.style.height='auto';input.style.height=Math.min(input.scrollHeight,118)+'px'} input.oninput=resizeInput;
function setMoreOpen(open){morePopover.classList.toggle('open',open);moreBtn.setAttribute('aria-expanded',open?'true':'false');window.__setMoreMorph?.(open)}
function setModelOpen(open){modelPopover.classList.toggle('open',open);window.__setModelMorph?.(open);if(open){modelView='main';renderModel()}}
function setSettingsOpen(open){settingsPopover.classList.toggle('open',open);settingsBtn.setAttribute('aria-expanded',open?'true':'false');window.__setSettingsMorph?.(open)}
function closeAll(){setMoreOpen(false);setModelOpen(false);setSettingsOpen(false)}
function setAnnivPicker(open){annivPicker.classList.toggle('open',open);annivPicker.setAttribute('aria-hidden',open?'false':'true');annivTrigger.setAttribute('aria-expanded',open?'true':'false');if(!open)document.querySelectorAll('.cute-select.open').forEach(x=>x.classList.remove('open'))}
function setDrawerOpen(open){app.classList.toggle('drawer-open',open);drawerLayer.classList.toggle('open',open);drawerLayer.setAttribute('aria-hidden',open?'false':'true');drawerBtn.setAttribute('aria-expanded',open?'true':'false');window.__setNavMorph?.(open);if(open)closeAll();else setAnnivPicker(false)}
function send(){const text=input.value.trim();if(!text){hint();return}const a=document.createElement('article');a.className='msg me';a.innerHTML='<div class="user-avatar">漾</div><div class="user-bubble"></div>';a.querySelector('.user-bubble').textContent=text;list.append(a);input.value='';resizeInput();window.__playSendMorph?.();requestAnimationFrame(()=>list.scrollTo({top:list.scrollHeight,behavior:'smooth'}))}
function rowHTML(item,selected){return `<button class="model-row${selected?' selected':''}" data-pick="${item.id}"><div><div class="model-name">${item.name}</div>${item.desc?`<div class="model-desc">${item.desc}</div>`:''}</div>${selected?'<span class="model-check">✓</span>':''}</button>`}
function gridHTML(items){return `<div class="more-model-grid">${items.map(m=>`<button class="more-model-chip${currentModel===m.id?' selected':''}" data-pick="${m.id}"><span>${m.name}</span>${currentModel===m.id?'<span class="chip-check">✓</span>':''}</button>`).join('')}</div>`}
function renderModel(){modelBack.style.visibility=modelView==='main'?'hidden':'visible';if(modelView==='main'){const effort=EFFORTS.find(e=>e.id===currentEffort)||EFFORTS[2];modelBody.innerHTML=MAIN_MODELS.map(m=>rowHTML(m,currentModel===m.id)).join('')+`<div class="model-navs"><button class="model-nav" data-view="effort"><strong>${effort.name}</strong><small>回复深度与速度</small></button><button class="model-nav more-nav" data-view="more"><strong>更多模型 / 1M</strong><small>Sonnet · Haiku ·<br>长上下文</small></button></div>`}else if(modelView==='effort'){modelBody.innerHTML=EFFORTS.map(e=>rowHTML(e,currentEffort===e.id)).join('')+'<div class="model-note">更高档位会更深入，但通常也会更慢。</div>'}else{modelBody.innerHTML=gridHTML(MORE_MODELS)+'<div class="more-view-title long-title"><span>1M</span><small>一百万上下文，少压缩</small></div><div class="long-list">'+LONG_MODELS.map(m=>rowHTML(m,currentModel===m.id)).join('')+'</div>'}modelBody.querySelectorAll('[data-view]').forEach(b=>b.onclick=e=>{e.stopPropagation();modelView=b.dataset.view;renderModel()});modelBody.querySelectorAll('[data-pick]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=b.dataset.pick;if(modelView==='effort'){const effort=EFFORTS.find(x=>x.id===id);if(!effort)return;currentEffort=effort.id;hint(`${effort.name} · 前端预览`);renderModel();return}const m=[...MAIN_MODELS,...MORE_MODELS,...LONG_MODELS].find(x=>x.id===id);if(!m)return;currentModel=m.id;modelBtnText.textContent=m.name.replace(' · 1M',' 1M');hint(`已切换到 ${m.name} · 前端预览`);renderModel()})}
const pad=n=>String(n).padStart(2,'0');
const RELATION_STORE='chaosheng-relationship-date-v1',TODO_STORE='chaosheng-drawer-todos-v1';
let relationStart=(()=>{const fallback={year:2026,month:7,day:14};try{return Object.assign(fallback,JSON.parse(localStorage.getItem(RELATION_STORE)||'{}'))}catch(e){return fallback}})();
let todoStore=(()=>{try{return JSON.parse(localStorage.getItem(TODO_STORE)||'{}')||{}}catch(e){return {}}})();
const WEEKDAYS=['SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY'];
const MONTHS=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];
const daysInMonth=(y,m)=>new Date(y,m,0).getDate();
function dayOfYear(d){return Math.floor((Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())-Date.UTC(d.getFullYear(),0,0))/86400000)}
function relationDays(d){return Math.max(0,Math.floor((Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())-Date.UTC(relationStart.year,relationStart.month-1,relationStart.day))/86400000))}
function localDayKey(d=new Date()){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function todayTodos(){const key=localDayKey();if(!todoStore[key]){todoStore[key]=[{id:'water',text:'今天喝水',done:false},{id:'parcel',text:'下午拿快递',done:false}];localStorage.setItem(TODO_STORE,JSON.stringify(todoStore))}return todoStore[key]}
function renderDrawerTodos(){drawerTodoList.innerHTML='';todayTodos().forEach(item=>{const b=document.createElement('button');b.type='button';b.className='todo-item'+(item.done?' done':'');b.innerHTML='<span class="todo-box"></span><span class="todo-text"></span>';b.querySelector('.todo-box').textContent=item.done?'✓':'';b.querySelector('.todo-text').textContent=item.text;b.onclick=e=>{e.stopPropagation();item.done=!item.done;localStorage.setItem(TODO_STORE,JSON.stringify(todoStore));renderDrawerTodos()};drawerTodoList.appendChild(b)})}
function updateDrawerClock(){const d=new Date(),days=relationDays(d);drawerTime.textContent=`${pad(d.getHours())}:${pad(d.getMinutes())}`;drawerDate.textContent=`${WEEKDAYS[d.getDay()]} · ${MONTHS[d.getMonth()]} ${pad(d.getDate())} · DAY ${dayOfYear(d)}`;drawerTogetherDays.textContent=days;drawerTogetherDayCaption.textContent=days}
function updateRelationshipPicker(){pickerDateText.textContent=`${relationStart.year}.${pad(relationStart.month)}.${pad(relationStart.day)}`;document.querySelector('[data-kind="year"] .cute-value').textContent=`${relationStart.year} 年`;document.querySelector('[data-kind="month"] .cute-value').textContent=`${pad(relationStart.month)} 月`;document.querySelector('[data-kind="day"] .cute-value').textContent=`${pad(relationStart.day)} 日`}
function optionList(kind){if(kind==='year'){const y=new Date().getFullYear();return Array.from({length:12},(_,i)=>y-9+i)}if(kind==='month')return Array.from({length:12},(_,i)=>i+1);return Array.from({length:daysInMonth(relationStart.year,relationStart.month)},(_,i)=>i+1)}
function optionLabel(kind,v){return kind==='year'?`${v} 年`:kind==='month'?`${pad(v)} 月`:`${pad(v)} 日`}
function renderSelect(select){const kind=select.dataset.kind,box=select.querySelector('.cute-options'),values=optionList(kind),current=relationStart[kind];box.innerHTML=values.map(v=>`<button class="cute-option${v===current?' selected':''}" type="button" data-value="${v}">${optionLabel(kind,v)}</button>`).join('');box.querySelectorAll('.cute-option').forEach(opt=>opt.onclick=e=>{e.stopPropagation();relationStart[kind]=Number(opt.dataset.value);if(kind!=='day')relationStart.day=Math.min(relationStart.day,daysInMonth(relationStart.year,relationStart.month));localStorage.setItem(RELATION_STORE,JSON.stringify(relationStart));updateRelationshipPicker();updateDrawerClock();document.querySelectorAll('.cute-select').forEach(renderSelect);select.classList.remove('open')})}
document.querySelectorAll('.cute-select').forEach(select=>{renderSelect(select);select.querySelector('.cute-select-btn').onclick=e=>{e.stopPropagation();const opening=!select.classList.contains('open');document.querySelectorAll('.cute-select.open').forEach(x=>x.classList.remove('open'));select.classList.toggle('open',opening)}});
updateRelationshipPicker();updateDrawerClock();renderDrawerTodos();setInterval(updateDrawerClock,30000);
annivTrigger.onclick=e=>{e.stopPropagation();setAnnivPicker(!annivPicker.classList.contains('open'))};annivPicker.onclick=e=>e.stopPropagation();
document.getElementById('send').onclick=send;input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};
drawerBtn.onclick=e=>{e.stopPropagation();setDrawerOpen(!drawerLayer.classList.contains('open'))};
drawerDim.onclick=e=>{e.stopPropagation();setDrawerOpen(false)};
sideDrawer.onclick=e=>e.stopPropagation();
drawerBack.onclick=e=>{e.stopPropagation();hint('返回首页 · 占位')};
const drawerRoutes={'回忆':'memory.html','相册':'album.html','日记':'diary.html','工作室':'studio.html','小窝':'nest.html'};
document.querySelectorAll('.drawer-link').forEach(btn=>btn.onclick=e=>{e.stopPropagation();const route=btn.dataset.route,target=drawerRoutes[route];if(target){location.href=target;return}setDrawerOpen(false);hint(`${route} · 预览跳转`)});
settingsBtn.onclick=e=>{e.stopPropagation();setMoreOpen(false);setModelOpen(false);setSettingsOpen(!settingsPopover.classList.contains('open'))};settingsPopover.onclick=e=>e.stopPropagation();document.querySelectorAll('.settings-item').forEach(btn=>btn.onclick=e=>{e.stopPropagation();hint(`${btn.dataset.setting} · 预览`)});moreBtn.onclick=e=>{e.stopPropagation();setSettingsOpen(false);setModelOpen(false);setMoreOpen(!morePopover.classList.contains('open'))};morePopover.onclick=e=>e.stopPropagation();modelBtn.onclick=e=>{e.stopPropagation();setSettingsOpen(false);setMoreOpen(false);setModelOpen(!modelPopover.classList.contains('open'))};modelPopover.onclick=e=>e.stopPropagation();modelClose.onclick=e=>{e.stopPropagation();setModelOpen(false)};modelBack.onclick=e=>{e.stopPropagation();modelView='main';renderModel()};thinkingSwitch.onclick=e=>{e.stopPropagation();thinkingOn=!thinkingOn;thinkingSwitch.classList.toggle('on',thinkingOn);thinkingSwitch.setAttribute('aria-pressed',thinkingOn?'true':'false');hint(`Thinking ${thinkingOn?'已开启':'已关闭'} · 前端预览`)};document.addEventListener('click',()=>{closeAll();setAnnivPicker(false)});document.querySelectorAll('.more-item').forEach(btn=>btn.onclick=()=>{hint(`${btn.dataset.action} · 预览`);setMoreOpen(false)});document.querySelector('.mic').onclick=()=>hint('语音暂未接入');document.getElementById('avatarToggle').onclick=()=>{const on=app.classList.toggle('show-avatar');hint(on?'已显示双方头像':'已隐藏双方头像')};requestAnimationFrame(()=>list.scrollTop=list.scrollHeight);
(async()=>{try{const [{createMorph},{Plus,X,ArrowRight,Check,Heart,Sparkles,ChevronDown,ChevronUp,Menu}]=await Promise.all([import('https://esm.sh/morphicons@1.5.0/dom'),import('https://esm.sh/lucide@1.28.0')]);const moreMorph=createMorph(document.getElementById('moreMorphPath'),Plus,{reducedMotion:'user'}),sendMorph=createMorph(document.getElementById('sendMorphPath'),ArrowRight,{reducedMotion:'user'}),settingsMorph=createMorph(document.getElementById('topMorphPath'),Heart,{reducedMotion:'user'}),modelMorph=createMorph(document.getElementById('modelChevronPath'),ChevronDown,{reducedMotion:'user'}),navMorph=createMorph(document.getElementById('navMorphPath'),Menu,{reducedMotion:'user'});let sendTimer;window.__setMoreMorph=o=>moreMorph.morphTo(o?X:Plus,'smooth');window.__setSettingsMorph=o=>settingsMorph.morphTo(o?Sparkles:Heart,'smooth');window.__setModelMorph=o=>modelMorph.morphTo(o?ChevronUp:ChevronDown,'smooth');window.__setNavMorph=o=>navMorph.morphTo(o?X:Menu,'smooth');window.__playSendMorph=()=>{clearTimeout(sendTimer);sendMorph.morphTo(Check,'snappy');sendTimer=setTimeout(()=>sendMorph.morphTo(ArrowRight,'smooth'),650)}}catch(err){console.warn('Morphicons preview fallback:',err)}})();