(()=>{
'use strict';
const $=s=>document.querySelector(s), messages=$('#messages'), KEY='chaosheng-chat-special-preview-v1';
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
const btn=(text,fn,cls='rich-btn')=>{const n=el('button',cls,text);n.type='button';n.onclick=fn;return n};
let state={tasks:[],reminder:null,draftHtml:'<div class="note">今天也一起慢慢来 ♡</div>',draftCss:'.note { padding: 24px; color: #906f79; background: #f4e5e9; border-radius: 18px 6px 18px 18px; }'};
try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&typeof s==='object'){if(Array.isArray(s.tasks))state.tasks=s.tasks.filter(t=>t&&typeof t.id==='string'&&typeof t.title==='string'&&['once','daily','cron'].includes(t.type)&&typeof t.rule==='string'&&typeof t.zone==='string').slice(0,100);if(s.reminder&&typeof s.reminder.text==='string')state.reminder=s.reminder;if(typeof s.draftHtml==='string')state.draftHtml=s.draftHtml.slice(0,30000);if(typeof s.draftCss==='string')state.draftCss=s.draftCss.slice(0,30000)}}catch{}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{hint('本次操作有效，但浏览器未能保存');return false}}
function url(value){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password?u.href:null}catch{return null}}
function dialog(id,title,markup){const d=el('dialog','rich-dialog');d.id=id;d.setAttribute('aria-labelledby',id+'Title');const inner=el('div','rich-inner'),head=el('div','rich-head'),h=el('h2','',title);h.id=id+'Title';const close=btn('×',()=>d.close(),'rich-close');close.setAttribute('aria-label','关闭'+title);head.append(h,close);inner.append(head);const content=el('div');content.innerHTML=markup;inner.append(content);d.append(inner);document.body.append(d);d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});return d}
function show(d){closeAll();setDrawerOpen(false);if(!d.open)d.showModal()}
function safeFragment(html){const doc=new DOMParser().parseFromString(html,'text/html'),out=document.createDocumentFragment();const allowed=new Set('P BR HR H1 H2 H3 H4 H5 H6 STRONG EM DEL BLOCKQUOTE UL OL LI PRE CODE TABLE THEAD TBODY TR TH TD A INPUT'.split(' '));function copy(n,parent){if(n.nodeType===3){parent.append(document.createTextNode(n.textContent));return}if(n.nodeType!==1)return;if(!allowed.has(n.tagName)){if(['SCRIPT','STYLE','IFRAME','OBJECT','SVG','MATH','FORM'].includes(n.tagName))return;for(const child of n.childNodes)copy(child,parent);return}const e=el(n.tagName.toLowerCase());if(n.tagName==='A'){const target=url(n.getAttribute('href'));if(target){e.href=target;e.onclick=ev=>{ev.preventDefault();openWeb(target)}}}if(n.tagName==='INPUT'){if(n.getAttribute('type')!=='checkbox')return;e.type='checkbox';e.disabled=true;e.checked=n.hasAttribute('checked')}for(const child of n.childNodes)copy(child,e);parent.append(e)}for(const child of doc.body.childNodes)copy(child,out);return out}
// Opaque-origin CSS/HTML canvas: no scripts, forms, same-origin, networking or navigation permission.
function canvas(frame,html,css){const fragment=safeFragment(html),box=el('div');box.append(fragment);const doc=new DOMParser().parseFromString(html,'text/html');const clean=el('div');const forbidden='script,iframe,object,embed,link,meta,base,svg,math,form,input,button,video,audio,source';doc.querySelectorAll(forbidden).forEach(n=>n.remove());doc.body.querySelectorAll('*').forEach(n=>{for(const a of [...n.attributes])if(!['class','style'].includes(a.name))n.removeAttribute(a.name);if(n.tagName==='A')n.replaceWith(document.createTextNode(n.textContent))});clean.innerHTML=doc.body.innerHTML;frame.setAttribute('sandbox','');frame.srcdoc='<!doctype html><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; img-src data:; font-src \'none\'; form-action \'none\'; base-uri \'none\'"><style>body{margin:12px;font:14px/1.6 sans-serif;overflow-wrap:anywhere}'+css.replace(/<\/style/gi,'<\\/style')+'</style>'+clean.innerHTML}
function markdown(text,target){target.classList.add('rich-md');if(!window.marked){target.textContent=text;return}target.replaceChildren(safeFragment(marked.parse(String(text),{gfm:true,breaks:true})));const blocks=[...String(text).matchAll(/```css\s*\n([\s\S]*?)```/g)];for(const m of blocks){const f=el('iframe','css-preview');f.title='CSS 独立展示';canvas(f,'<div class="note">小窝里的小纸条 ♡</div>',m[1]);target.append(f)}}
function bubble(role='sheng'){const a=el('article','msg '+(role==='me'?'me':'sheng')+' rich-msg');if(role==='me'){a.append(el('div','user-avatar','漾'))}else{const avatar=el('img','avatar avatar-sheng');avatar.src='https://files.catbox.moe/ge809e.png';avatar.alt='';const meta=el('div','assistant-meta');meta.append(el('span','time',new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})),el('span','rich-meta','展示示例'));a.append(avatar,meta)}const body=el('div',role==='me'?'user-bubble':'assistant-text');a.append(body);messages.append(a);requestAnimationFrame(()=>messages.scrollTo({top:messages.scrollHeight,behavior:'smooth'}));return body}
function card(role,title,sub,action,label){const c=el('div','rich-card');c.append(el('strong','',title),el('small','',sub));if(action)c.append(btn(label,action));bubble(role).append(c);return c}
function song(role,title,artist){const c=el('div','rich-card rich-song'),img=el('img');img.src='https://iili.io/ndLTEBI.png';img.alt='歌曲唱片';const info=el('span');info.append(el('strong','',title),el('small','',artist+' · 分享示例'),btn('打开唱片室',()=>{location.href='music.html?v=chat-special-1&previewSong='+encodeURIComponent(title)}));c.append(img,info);bubble(role).append(c)}
const webDialog=dialog('richWeb','小窗浏览','<form class="rich-browser-form" id="richUrlForm"><input type="url" class="rich-field" id="richUrl" placeholder="https://…" aria-label="网页地址" required><button class="rich-btn" type="submit">打开</button></form><p class="rich-error" id="richUrlError" role="status"></p><div class="rich-stack"><a class="rich-btn" id="richExternal" target="_blank" rel="noopener noreferrer" hidden>外部打开</a><button class="rich-btn" id="richShareUrl">分享这个网址</button></div><p class="rich-note">部分网站不允许在小窗显示；空白或无法登录时，请点“外部打开”。</p><iframe class="rich-webframe" id="richWebFrame" sandbox="allow-scripts allow-forms" referrerpolicy="no-referrer" title="网页浏览窗口"></iframe>');
let currentUrl='';function openWeb(value){show(webDialog);if(value){$('#richUrl').value=value;loadWeb(value)}}function loadWeb(value){const u=url(value);if(!u){$('#richUrlError').textContent='请填写完整的 http 或 https 网址。';return}if(location.protocol==='https:'&&u.startsWith('http:')){$('#richUrlError').textContent='这个网址使用 http，请通过外部打开查看。';$('#richWebFrame').src='about:blank'}else{$('#richUrlError').textContent='已尝试加载网页；若未显示，可用外部打开。';$('#richWebFrame').src=u}currentUrl=u;$('#richExternal').href=u;$('#richExternal').hidden=false}$('#richUrlForm').onsubmit=e=>{e.preventDefault();loadWeb($('#richUrl').value.trim())};$('#richShareUrl').onclick=()=>{if(!currentUrl)return hint('先打开一个网址');const u=currentUrl;card('me',new URL(u).hostname,u,()=>openWeb(u),'查看网页');webDialog.close()};webDialog.addEventListener('close',()=>{$('#richWebFrame').src='about:blank'});
const tasksDialog=dialog('richCron','小定时器','<p class="rich-note">前端任务草稿 · 不会后台计时或发通知。可以点“试响”查看声声的提醒。</p><div id="richTaskList"></div><form id="richTaskForm"><label for="richTaskTitle">提醒什么</label><input class="rich-field" id="richTaskTitle" maxlength="100" placeholder="休息一下，喝口水" required><label for="richTaskType">什么时候</label><select class="rich-field" id="richTaskType"><option value="once">只提醒一次</option><option value="daily">每天</option><option value="cron">Cron 表达式</option></select><label id="richRuleLabel" for="richTaskRule">日期与时间</label><input class="rich-field" id="richTaskRule" type="datetime-local" required><p class="rich-note" id="richTaskZone"></p><p class="rich-error" id="richTaskError" role="status"></p><button class="rich-btn" type="submit">保存任务草稿</button></form>');
const zone=Intl.DateTimeFormat().resolvedOptions().timeZone||'本机时间';$('#richTaskZone').textContent='时区：'+zone;
function cronValid(rule){const parts=rule.trim().split(/\s+/),limits=[[0,59],[0,23],[1,31],[1,12],[0,7]];if(parts.length!==5)return false;return parts.every((field,i)=>field.split(',').every(item=>{const m=item.match(/^(\*|\d+(?:-\d+)?)(?:\/(\d+))?$/);if(!m||m[2]&&(+m[2]<1||+m[2]>limits[i][1]+1))return false;if(m[1]==='*')return true;const nums=m[1].split('-').map(Number);return nums.every(n=>n>=limits[i][0]&&n<=limits[i][1])&&(nums.length===1||nums[0]<=nums[1])}))}
$('#richTaskType').onchange=()=>{const t=$('#richTaskType').value,r=$('#richTaskRule');r.type=t==='once'?'datetime-local':t==='daily'?'time':'text';r.value='';r.placeholder=t==='cron'?'0 9 * * *':'';$('#richRuleLabel').textContent=t==='cron'?'分 时 日 月 周（标准五段）':t==='daily'?'每天几点':'日期与时间'};
function taskText(t){return(t.type==='daily'?'每天 ':t.type==='once'?'一次 · ':'Cron · ')+t.rule+' · '+t.zone+' · '+(t.paused?'已暂停':'草稿，待接入')}
function renderTasks(){const box=$('#richTaskList');box.replaceChildren();if(!state.tasks.length)box.append(el('p','rich-note','还没有定时任务。'));for(const t of state.tasks){const row=el('div','rich-task');row.append(el('strong','',t.title),el('small','',taskText(t)));const actions=el('div','rich-stack');actions.append(btn(t.paused?'继续':'暂停',()=>{t.paused=!t.paused;persist();renderTasks()}),btn('试响',()=>{if(t.paused)return hint('这个草稿已暂停');remind(t.title);tasksDialog.close()}),btn('发到聊天',()=>{card('sheng',t.title,taskText(t),()=>{renderTasks();show(tasksDialog)},'查看定时器');tasksDialog.close()}),btn('移除',()=>{state.tasks=state.tasks.filter(x=>x.id!==t.id);persist();renderTasks()}));row.append(actions);box.append(row)}}
$('#richTaskForm').onsubmit=e=>{e.preventDefault();const title=$('#richTaskTitle').value.trim(),type=$('#richTaskType').value,rule=$('#richTaskRule').value.trim(),error=$('#richTaskError');error.textContent='';if(!title)return;if(type==='cron'&&!cronValid(rule)){error.textContent='这个表达式还不对，例如：0 9 * * *（每天 9 点）。';return}if(type==='once'&&(!Number.isFinite(new Date(rule).getTime())||new Date(rule).getTime()<=Date.now())){error.textContent='请选择一个将来的时间。';return}if(type==='daily'&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(rule)){error.textContent='请填写有效时间。';return}if(state.tasks.length>=100){error.textContent='草稿已满，请先移除不用的任务。';return}state.tasks.push({id:'preview-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),title,type,rule,zone,paused:false});const ok=persist();renderTasks();$('#richTaskTitle').value='';error.textContent=ok?'草稿已保存，接入后才会定时触发。':'当前页面已保留，但浏览器保存失败。'};
const pin=el('aside','rich-pin');pin.hidden=true;pin.setAttribute('aria-label','声声的常驻提醒');pin.innerHTML='<div class="rich-head"><strong>声声的提醒 · 示例</strong><button class="rich-btn" id="richMinPin">收起</button></div><div class="pin-body"><p id="richPinText" role="status"></p><button class="rich-btn alt" id="richAckPin">知道啦</button></div>';document.body.append(pin);
function renderPin(){pin.hidden=!state.reminder;if(!state.reminder)return;pin.dataset.mini=state.reminder.mini?'true':'false';$('#richPinText').textContent=state.reminder.text;$('#richMinPin').textContent=state.reminder.mini?'展开':'收起'}function remind(text){state.reminder={text:String(text).slice(0,1000),mini:false};persist();renderPin()}$('#richMinPin').onclick=()=>{state.reminder.mini=!state.reminder.mini;persist();renderPin()};$('#richAckPin').onclick=()=>{state.reminder=null;persist();renderPin()};renderPin();
const terminal=dialog('richTerminal','小终端','<p class="rich-note">演示终端 · 未连接 Termux。这里不会执行真实命令。关闭后草稿仍在。</p><pre class="rich-terminal" id="richTerminalLog" aria-label="终端输出"></pre><form class="rich-command" id="richCommandForm"><input class="rich-field" id="richCommand" placeholder="输入 help 看看" maxlength="1000" aria-label="演示命令" autocomplete="off" autocapitalize="off" spellcheck="false"><button class="rich-btn" type="submit">发送</button></form><details style="margin-top:15px"><summary>小改一下 · HTML / CSS 草稿</summary><label for="richHtml">HTML</label><textarea class="rich-field rich-draft" id="richHtml" maxlength="30000" spellcheck="false"></textarea><label for="richCss">CSS</label><textarea class="rich-field rich-draft" id="richCss" maxlength="30000" spellcheck="false"></textarea><div class="rich-stack"><button class="rich-btn" id="richDraftPreview">更新预览</button><button class="rich-btn" id="richDraftCopy">复制代码</button></div><iframe class="rich-draft-frame" id="richDraftFrame" sandbox="" title="独立代码草稿预览"></iframe><p class="rich-note">草稿仅保存在本机，预览支持静态 HTML / CSS。</p></details>');
let lines=['潮生 · 小终端演示','输入 help 查看可用命令；真实执行将在接入后开放。'];const log=()=>{$('#richTerminalLog').textContent=lines.join('\n');$('#richTerminalLog').scrollTop=$('#richTerminalLog').scrollHeight};function command(raw){const value=raw.trim();if(!value)return;if(value==='clear')lines=[];else{lines.push('漾 › '+value);if(value==='help')lines.push('help · 帮助\nclear · 清屏\npwd · 查看演示路径\nls · 查看草稿\necho 文字 · 回显');else if(value==='pwd')lines.push('/preview/drafts（演示路径）');else if(value==='ls')lines.push('draft.html  draft.css（下方草稿编辑器）');else if(value.startsWith('echo '))lines.push(value.slice(5));else lines.push('未执行：终端尚未连接。可以先用下方编辑器微调草稿。')}lines=lines.slice(-100);log()}$('#richCommandForm').onsubmit=e=>{e.preventDefault();command($('#richCommand').value);$('#richCommand').value=''};log();$('#richHtml').value=state.draftHtml;$('#richCss').value=state.draftCss;
function saveDraft(){state.draftHtml=$('#richHtml').value;state.draftCss=$('#richCss').value;persist()}$('#richHtml').oninput=saveDraft;$('#richCss').oninput=saveDraft;$('#richDraftPreview').onclick=()=>{saveDraft();canvas($('#richDraftFrame'),state.draftHtml,state.draftCss)};$('#richDraftCopy').onclick=async()=>{try{await navigator.clipboard.writeText('<style>\n'+$('#richCss').value+'\n</style>\n'+$('#richHtml').value);hint('已复制草稿')}catch{hint('无法自动复制，可以长按代码选择复制')}};canvas($('#richDraftFrame'),state.draftHtml,state.draftCss);

// Visible in-conversation fixtures: no extra composer menu or sample launcher.
markdown('这首歌想和你一起听。',bubble('sheng'));
const firstSpecial=messages.lastElementChild;
song('sheng','晚风来信','示例曲目 · 轻柔钢琴');
markdown('那我也给你分享一首 ouo',bubble('me'));
song('me','靠近一点','示例曲目 · 木吉他');
card('sheng','给你留了一个网页','在聊天里打开看看。',()=>openWeb('https://example.com/'),'打开网页');
card('sheng','15:00 · 提醒你休息一下','每天 · 定时任务样式预览',()=>{renderTasks();show(tasksDialog)},'查看定时器');
card('sheng','忙完记得喝口水 ♡','声声的提醒',()=>remind('忙完这件事，记得喝口水。我在这里。'),'展开提醒');
markdown('要微调的代码可以在这里打开，改完收起来就好。',bubble('sheng'));
card('sheng','小终端','代码草稿 · 未连接真实终端',()=>show(terminal),'打开');
markdown('**今天的小便签**\n\n> 慢慢来，我陪你。\n\n- [x] 把喜欢的歌分享给你\n- [ ] 一起听完\n\n```css\n.note { padding:20px; background:#f0e3e8; color:#936e7a; border-radius:18px 5px 18px 18px; }\n```',bubble('sheng'));
requestAnimationFrame(()=>messages.scrollTo({top:Math.max(0,firstSpecial.offsetTop-messages.offsetTop-16),behavior:'instant'}));

try{const shared=JSON.parse(sessionStorage.getItem('chaosheng-song-share-preview'));if(shared&&typeof shared.title==='string'){song('me',shared.title.slice(0,100),String(shared.artist||'').slice(0,100));sessionStorage.removeItem('chaosheng-song-share-preview')}}catch{}
// Use the same safe rich-text renderer for new user messages; never evaluate message code.
function sendRich(){const input=$('#input'),text=input.value.trim();if(!text)return hint('慢慢说…');if(url(text)){const u=url(text);card('me',new URL(u).hostname,u,()=>openWeb(u),'查看网页')}else markdown(text,bubble('me'));input.value='';resizeInput();window.__playSendMorph?.()}
$('#send').onclick=sendRich;$('#input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();sendRich()}};
// Future structured-message adapter. Only explicit typed cards; no terminal execution bridge.
window.ChatSpecialPreview={appendMessage(message){const role=message.role==='me'?'me':'sheng';if(message.type==='song')song(role,String(message.title||'分享一首歌'),String(message.artist||''));else if(message.type==='web'){const u=url(message.url);if(u)card(role,new URL(u).hostname,u,()=>openWeb(u),'查看网页')}else if(message.type==='reminder')card(role,'声声的提醒',String(message.text||''),()=>remind(message.text),'查看提醒');else if(message.type==='terminal')card(role,'小终端','演示入口',()=>show(terminal),'打开小终端');else if(message.type==='cron')card(role,'定时任务',String(message.text||'任务展示'),()=>{renderTasks();show(tasksDialog)},'查看定时器');else markdown(String(message.text||''),bubble(role))},openTerminal:()=>show(terminal)};
})();
