(()=>{
'use strict';
const $=s=>document.querySelector(s), messages=$('#messages'), KEY='chaosheng-chat-special-preview-v1';
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
const btn=(text,fn,cls='rich-btn')=>{const n=el('button',cls,text);n.type='button';n.onclick=fn;return n};
let state={tasks:[],reminder:null,draftHtml:'<div class="note">今天也一起慢慢来 ♡</div>',draftCss:'.note { padding: 24px; color: #906f79; background: #f4e5e9; border-radius: 18px 6px 18px 18px; }'};
try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&typeof s==='object'){if(Array.isArray(s.tasks))state.tasks=s.tasks.filter(t=>t&&typeof t.id==='string'&&typeof t.title==='string'&&['once','daily','cron'].includes(t.type)&&typeof t.rule==='string'&&typeof t.zone==='string').slice(0,100);if(s.reminder&&typeof s.reminder.text==='string')state.reminder=s.reminder;if(typeof s.draftHtml==='string')state.draftHtml=s.draftHtml.slice(0,30000);if(typeof s.draftCss==='string')state.draftCss=s.draftCss.slice(0,30000)}}catch{}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{hint('本次操作有效，但浏览器未能保存');return false}}
function url(value){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password?u.href:null}catch{return null}}
function dialog(id,title,markup){const d=el('dialog','rich-dialog');d.id=id;d.setAttribute('aria-labelledby',id+'Title');const inner=el('div','rich-inner'),head=el('div','rich-head'),h=el('h2','',title);h.id=id+'Title';const close=btn('×',()=>d.close(),'rich-close');close.setAttribute('aria-label','关闭'+title);head.append(h,close);inner.append(head);const content=el('div');content.innerHTML=markup;inner.append(content);d.append(inner);document.body.append(d);d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});return d}
function show(d){closeAll();setDrawerOpen(false);if(!d.open)d.showModal()}
function safeFragment(html){const doc=new DOMParser().parseFromString(html,'text/html'),out=document.createDocumentFragment();const allowed=new Set('P BR HR H1 H2 H3 H4 H5 H6 STRONG EM DEL BLOCKQUOTE UL OL LI PRE CODE TABLE THEAD TBODY TR TH TD A INPUT'.split(' '));function copy(n,parent){if(n.nodeType===3){parent.append(document.createTextNode(n.textContent));return}if(n.nodeType!==1)return;if(!allowed.has(n.tagName)){if(['SCRIPT','STYLE','IFRAME','OBJECT','SVG','MATH','FORM'].includes(n.tagName))return;for(const child of n.childNodes)copy(child,parent);return}const e=el(n.tagName.toLowerCase());if(n.tagName==='A'){const target=url(n.getAttribute('href'));if(target){e.href=target;e.onclick=ev=>{ev.preventDefault();openWeb(target)}}}if(n.tagName==='INPUT'){if(n.getAttribute('type')!=='checkbox')return;e.type='checkbox';e.disabled=true;e.checked=n.hasAttribute('checked')}for(const child of n.childNodes)copy(child,e);parent.append(e)}for(const child of doc.body.childNodes)copy(child,out);return out}
// Opaque-origin CSS/HTML canvas: no scripts, forms, same-origin, networking or navigation permission.
function canvas(frame,html,css){const fragment=safeFragment(html),box=el('div');box.append(fragment);const doc=new DOMParser().parseFromString(html,'text/html');const clean=el('div');const forbidden='script,iframe,object,embed,link,meta,base,svg,math,form,input,button,video,audio,source';doc.querySelectorAll(forbidden).forEach(n=>n.remove());doc.body.querySelectorAll('*').forEach(n=>{for(const a of [...n.attributes])if(!['class','style'].includes(a.name))n.removeAttribute(a.name);if(n.tagName==='A')n.replaceWith(document.createTextNode(n.textContent))});clean.innerHTML=doc.body.innerHTML;frame.setAttribute('sandbox','');frame.srcdoc='<!doctype html><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; img-src data:; font-src \'none\'; form-action \'none\'; base-uri \'none\'"><style>body{margin:12px;font:14px/1.6 sans-serif;overflow-wrap:anywhere}'+css.replace(/<\/style/gi,'<\\/style')+'</style>'+clean.innerHTML}
function markdown(text,target){target.classList.add('rich-md');if(!window.marked){target.textContent=text;return}target.replaceChildren(safeFragment(marked.parse(String(text),{gfm:true,breaks:true})));const blocks=[...String(text).matchAll(/```css\s*\n([\s\S]*?)```/g)];for(const m of blocks){const f=el('iframe','css-preview');f.title='CSS 独立展示';canvas(f,'<div class="note">小窝里的小纸条 ♡</div>',m[1]);target.append(f)}}
function bubble(role='sheng'){const a=el('article','msg '+(role==='me'?'me':'sheng')+' rich-msg');if(role==='me'){a.append(el('div','user-avatar','漾'))}else{const avatar=el('img','avatar avatar-sheng');avatar.src='https://files.catbox.moe/ge809e.png';avatar.alt='';const meta=el('div','assistant-meta');meta.append(el('span','time',new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})),el('span','rich-meta','展示示例'));a.append(avatar,meta)}const body=el('div',role==='me'?'user-bubble':'assistant-text');a.append(body);messages.append(a);requestAnimationFrame(()=>messages.scrollTo({top:messages.scrollHeight,behavior:'smooth'}));return body}
function card(role,title,sub,action,label){const c=el('div','rich-card');c.append(el('strong','',title),el('small','',sub));if(action)c.append(btn(label,action));bubble(role).append(c);return c}
const webDialog=dialog('richWeb','小窗浏览','<form class="rich-browser-form" id="richUrlForm"><input type="url" class="rich-field" id="richUrl" placeholder="https://…" aria-label="网页地址" required><button class="rich-btn" type="submit">打开</button></form><p class="rich-error" id="richUrlError" role="status"></p><div class="rich-stack"><a class="rich-btn" id="richExternal" target="_blank" rel="noopener noreferrer" hidden>外部打开</a><button class="rich-btn" id="richShareUrl">分享这个网址</button></div><p class="rich-note">部分网站不允许在小窗显示；空白或无法登录时，请点“外部打开”。</p><iframe class="rich-webframe" id="richWebFrame" sandbox="allow-scripts allow-forms" referrerpolicy="no-referrer" title="网页浏览窗口"></iframe>');
let currentUrl='';function openWeb(value){show(webDialog);if(value){$('#richUrl').value=value;loadWeb(value)}}function loadWeb(value){const u=url(value);if(!u){$('#richUrlError').textContent='请填写完整的 http 或 https 网址。';return}if(location.protocol==='https:'&&u.startsWith('http:')){$('#richUrlError').textContent='这个网址使用 http，请通过外部打开查看。';$('#richWebFrame').src='about:blank'}else{$('#richUrlError').textContent='已尝试加载网页；若未显示，可用外部打开。';$('#richWebFrame').src=u}currentUrl=u;$('#richExternal').href=u;$('#richExternal').hidden=false}$('#richUrlForm').onsubmit=e=>{e.preventDefault();loadWeb($('#richUrl').value.trim())};$('#richShareUrl').onclick=()=>{if(!currentUrl)return hint('先打开一个网址');const u=currentUrl;card('me',new URL(u).hostname,u,()=>openWeb(u),'查看网页');webDialog.close()};webDialog.addEventListener('close',()=>{$('#richWebFrame').src='about:blank'});
const tasksDialog=dialog('richCron','小定时器','<p class="rich-note">前端任务草稿 · 不会后台计时或发通知。可以点“试响”查看声声的提醒。</p><div id="richTaskList"></div><form id="richTaskForm"><label for="richTaskTitle">提醒什么</label><input class="rich-field" id="richTaskTitle" maxlength="100" placeholder="休息一下，喝口水" required><label for="richTaskType">什么时候</label><select class="rich-field" id="richTaskType"><option value="once">只提醒一次</option><option value="daily">每天</option><option value="cron">Cron 表达式</option></select><label id="richRuleLabel" for="richTaskRule">日期与时间</label><input class="rich-field" id="richTaskRule" type="datetime-local" required><p class="rich-note" id="richTaskZone"></p><p class="rich-error" id="richTaskError" role="status"></p><button class="rich-btn" type="submit">保存任务草稿</button></form>');
const zone=Intl.DateTimeFormat().resolvedOptions().timeZone||'本机时间';$('#richTaskZone').textContent='时区：'+zone;
function cronValid(rule){const parts=rule.trim().split(/\s+/),limits=[[0,59],[0,23],[1,31],[1,12],[0,7]];if(parts.length!==5)return false;return parts.every((field,i)=>field.split(',').every(item=>{const m=item.match(/^(\*|\d+(?:-\d+)?)(?:\/(\d+))?$/);if(!m||m[2]&&(+m[2]<1||+m[2]>limits[i][1]+1))return false;if(m[1]==='*')return true;const nums=m[1].split('-').map(Number);return nums.every(n=>n>=limits[i][0]&&n<=limits[i][1])&&(nums.length===1||nums[0]<=nums[1])}))}
$('#richTaskType').onchange=()=>{const t=$('#richTaskType').value,r=$('#richTaskRule');r.type=t==='once'?'datetime-local':t==='daily'?'time':'text';r.value='';r.placeholder=t==='cron'?'0 9 * * *':'';$('#richRuleLabel').textContent=t==='cron'?'分 时 日 月 周（标准五段）':t==='daily'?'每天几点':'日期与时间'};
function taskText(t){return(t.type==='daily'?'每天 ':t.type==='once'?'一次 · ':'Cron · ')+t.rule+' · '+t.zone+' · '+(t.paused?'已暂停':'草稿，待接入')}
function renderTasks(){const box=$('#richTaskList');box.replaceChildren();if(!state.tasks.length)box.append(el('p','rich-note','还没有定时任务。'));for(const t of state.tasks){const row=el('div','rich-task');row.append(el('strong','',t.title),el('small','',taskText(t)));const actions=el('div','rich-stack');actions.append(btn(t.paused?'继续':'暂停',()=>{t.paused=!t.paused;persist();renderTasks()}),btn('试响',()=>{if(t.paused)return hint('这个草稿已暂停');remind(t.title);tasksDialog.close()}),btn('发到聊天',()=>{card('sheng',t.title,taskText(t),()=>{renderTasks();show(tasksDialog)},'查看定时器');tasksDialog.close()}),btn('移除',()=>{state.tasks=state.tasks.filter(x=>x.id!==t.id);persist();renderTasks()}));row.append(actions);box.append(row)}}
$('#richTaskForm').onsubmit=e=>{e.preventDefault();const title=$('#richTaskTitle').value.trim(),type=$('#richTaskType').value,rule=$('#richTaskRule').value.trim(),error=$('#richTaskError');error.textContent='';if(!title)return;if(type==='cron'&&!cronValid(rule)){error.textContent='这个表达式还不对，例如：0 9 * * *（每天 9 点）。';return}if(type==='once'&&(!Number.isFinite(new Date(rule).getTime())||new Date(rule).getTime()<=Date.now())){error.textContent='请选择一个将来的时间。';return}if(type==='daily'&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(rule)){error.textContent='请填写有效时间。';return}if(state.tasks.length>=100){error.textContent='草稿已满，请先移除不用的任务。';return}state.tasks.push({id:'preview-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),title,type,rule,zone,paused:false});const ok=persist();renderTasks();$('#richTaskTitle').value='';error.textContent=ok?'草稿已保存，接入后才会定时触发。':'当前页面已保留，但浏览器保存失败。'};
const pin=el('aside','rich-pin');pin.hidden=true;pin.setAttribute('aria-label','声声的常驻提醒');pin.innerHTML='<div class="rich-head"><strong>声声的提醒 · 示例</strong><button class="rich-btn" id="richMinPin">收起</button></div><div class="pin-body"><p id="richPinText" role="status"></p><button class="rich-btn alt" id="richAckPin">知道啦</button></div>';document.body.append(pin);
function renderPin(){pin.hidden=!state.reminder;if(!state.reminder)return;pin.dataset.mini=state.reminder.mini?'true':'false';$('#richPinText').textContent=state.reminder.text;$('#richMinPin').textContent=state.reminder.mini?'展开':'收起'}function remind(text){state.reminder={text:String(text).slice(0,1000),mini:false};persist();renderPin()}$('#richMinPin').onclick=()=>{state.reminder.mini=!state.reminder.mini;persist();renderPin()};$('#richAckPin').onclick=()=>{state.reminder=null;persist();renderPin()};renderPin();
const terminal=dialog('richTerminal','小终端','<p class="rich-note">演示终端 · 未连接 Termux。这里不会执行真实命令。关闭后草稿仍在。</p><pre class="rich-terminal" id="richTerminalLog" aria-label="终端输出"></pre><form class="rich-command" id="richCommandForm"><input class="rich-field" id="richCommand" placeholder="输入 help 看看" maxlength="1000" aria-label="演示命令" autocomplete="off" autocapitalize="off" spellcheck="false"><button class="rich-btn" type="submit">发送</button></form><details style="margin-top:15px"><summary>小改一下 · HTML / CSS 草稿</summary><label for="richHtml">HTML</label><textarea class="rich-field rich-draft" id="richHtml" maxlength="30000" spellcheck="false"></textarea><label for="richCss">CSS</label><textarea class="rich-field rich-draft" id="richCss" maxlength="30000" spellcheck="false"></textarea><div class="rich-stack"><button class="rich-btn" id="richDraftPreview">更新预览</button><button class="rich-btn" id="richDraftCopy">复制代码</button></div><iframe class="rich-draft-frame" id="richDraftFrame" sandbox="" title="独立代码草稿预览"></iframe><p class="rich-note">草稿仅保存在本机，预览支持静态 HTML / CSS。</p></details>');
let lines=['潮生 · 小终端演示','输入 help 查看可用命令；真实执行将在接入后开放。'];const log=()=>{$('#richTerminalLog').textContent=lines.join('\n');$('#richTerminalLog').scrollTop=$('#richTerminalLog').scrollHeight};function command(raw){const value=raw.trim();if(!value)return;if(value==='clear')lines=[];else{lines.push('漾 › '+value);if(value==='help')lines.push('help · 帮助\nclear · 清屏\npwd · 查看演示路径\nls · 查看草稿\necho 文字 · 回显');else if(value==='pwd')lines.push('/preview/drafts（演示路径）');else if(value==='ls')lines.push('draft.html  draft.css（下方草稿编辑器）');else if(value.startsWith('echo '))lines.push(value.slice(5));else lines.push('未执行：终端尚未连接。可以先用下方编辑器微调草稿。')}lines=lines.slice(-100);log()}$('#richCommandForm').onsubmit=e=>{e.preventDefault();command($('#richCommand').value);$('#richCommand').value=''};log();$('#richHtml').value=state.draftHtml;$('#richCss').value=state.draftCss;
function saveDraft(){state.draftHtml=$('#richHtml').value;state.draftCss=$('#richCss').value;persist()}$('#richHtml').oninput=saveDraft;$('#richCss').oninput=saveDraft;$('#richDraftPreview').onclick=()=>{saveDraft();canvas($('#richDraftFrame'),state.draftHtml,state.draftCss)};$('#richDraftCopy').onclick=async()=>{try{await navigator.clipboard.writeText('<style>\n'+$('#richCss').value+'\n</style>\n'+$('#richHtml').value);hint('已复制草稿')}catch{hint('无法自动复制，可以长按代码选择复制')}};canvas($('#richDraftFrame'),state.draftHtml,state.draftCss);


// Message-native components. Kept inside chat-rich.js's closure on integration.
const fmt=seconds=>{const n=Math.max(0,Math.floor(seconds));return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')};
const mediaStates=[],terminalViews=[];let playingMedia=null;
function mediaButton(label,kind,fn){const b=btn('',fn,'cc-icon');b.setAttribute('aria-label',label);const paths={play:'M8 5l11 7-11 7Z',pause:'M8 5v14M16 5v14',expand:'M14 4h6v6M20 4l-7 7M10 20H4v-6M4 20l7-7',link:'M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-2 2M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l2-2',code:'m8 7-5 5 5 5m8-10 5 5-5 5m-3-13-2 16',image:'M4 4h16v16H4ZM4 16l5-6 4 4 3-3 4 5',clock:'M12 7v5l3 2M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20'};b.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="'+paths[kind]+'"></path></svg>';return b}
function nativeMessage(role,component){const body=bubble(role);body.classList.add('cc-message');body.append(component);return component}
function infoCard(role,title,description,kind,fn){const root=el('div','cc-artifact');const face=mediaButton(title,kind,fn),text=btn('',fn,'cc-artifact-copy');text.append(el('strong','',title),el('small','',description));root.append(face,text);nativeMessage(role,root);return root}
function toggleMedia(s){if(playingMedia&&playingMedia!==s){playingMedia.position=(Date.now()-playingMedia.started)/1000;playingMedia.playing=false}if(s.playing){s.position=(Date.now()-s.started)/1000;s.playing=false;playingMedia=null}else{if(s.position>=s.duration)s.position=0;s.started=Date.now()-s.position*1000;s.playing=true;playingMedia=s}mediaStates.forEach(updateMedia)}
function updateMedia(s){if(s.playing)s.position=Math.min(s.duration,(Date.now()-s.started)/1000);if(s.position>=s.duration){s.playing=false;if(playingMedia===s)playingMedia=null}s.clock.textContent=fmt(s.position)+' / '+fmt(s.duration);s.bar.style.width=(s.position/s.duration*100)+'%';s.play.setAttribute('aria-label',s.playing?'暂停播放演示':'播放演示');s.play.setAttribute('aria-pressed',String(s.playing));s.play.querySelector('path').setAttribute('d',s.playing?'M8 5v14M16 5v14':'M8 5l11 7-11 7Z');s.node.classList.toggle('is-playing',s.playing);if(lyricState===s)updateLyrics()}
const lyricsDialog=dialog('ccLyrics','一起听','<div id="ccLyricInfo"></div><div class="cc-lyric-lines" id="ccLyricLines"></div><div class="rich-stack" id="ccLyricControls"></div><p class="rich-note">歌词排版演示 · 以下为自拟文字，尚未连接歌曲音源。</p>');lyricsDialog.classList.add('cc-bottom-sheet');let lyricState=null;
const lyricSamples=['把窗边的晚风','轻轻留给你','等灯光慢慢落下来','我们再听一首歌','今天的心事不着急','有我陪着你'];
function openLyrics(s){lyricState=s;$('#ccLyricInfo').replaceChildren(el('strong','',s.title),el('p','rich-note',s.artist));$('#ccLyricLines').replaceChildren(...lyricSamples.map(text=>el('p','',text)));$('#ccLyricControls').replaceChildren(btn(s.playing?'暂停演示':'播放演示',()=>toggleMedia(s)),btn('从头播放',()=>{s.position=0;s.started=Date.now();if(!s.playing)toggleMedia(s);updateMedia(s)}));updateLyrics();show(lyricsDialog)}
function updateLyrics(){if(!lyricState)return;const active=Math.min(lyricSamples.length-1,Math.floor(lyricState.position/5));[...$('#ccLyricLines').children].forEach((p,i)=>p.classList.toggle('active',i===active));const b=$('#ccLyricControls').firstElementChild;if(b)b.textContent=lyricState.playing?'暂停演示':'播放演示'}
lyricsDialog.addEventListener('close',()=>{lyricState=null});
function song(role,title,artist){const root=el('div','cc-song'),open=btn('',()=>openLyrics(s),'cc-song-info'),img=el('img');img.src='https://iili.io/ndLTEBI.png';img.alt='';const text=el('span');text.append(el('strong','',title),el('small','',artist));open.append(img,text);const controls=el('div','cc-song-controls'),clock=el('span','cc-time'),track=el('div','cc-track'),bar=el('i');track.append(bar);const play=mediaButton('播放演示','play',()=>toggleMedia(s));controls.append(clock,play);root.append(open,track,controls,el('small','cc-caption','播放 / 歌词演示 · 暂无音源'));const s={title,artist,node:root,clock,bar,play,duration:180,position:0,playing:false,started:0};mediaStates.push(s);nativeMessage(role,root);updateMedia(s);return root}
function voice(role,text){const root=el('div','cc-voice-wrap'),strip=el('div','cc-voice'),wave=el('div','cc-wave');for(const h of [10,21,15,29,18,25,12,20]){const bar=el('i');bar.style.height=h+'px';wave.append(bar)}const clock=el('span','cc-time'),track=el('div','cc-track'),bar=el('i');track.append(bar);const play=mediaButton('播放语音演示','play',()=>toggleMedia(s));strip.append(play,wave,clock);root.append(strip,track,el('small','cc-caption','语音条示例 · 暂无音源'));const transcript=el('details','cc-transcript');transcript.append(el('summary','','文字'),el('p','',text));root.append(transcript);const s={node:root,clock,bar,play,duration:3,position:0,playing:false,started:0};mediaStates.push(s);nativeMessage(role,root);updateMedia(s)}
const artifactDialog=dialog('ccArtifact','小纸条','<iframe id="ccArtifactFrame" class="rich-draft-frame cc-artifact-frame" sandbox="" title="HTML 作品预览"></iframe><div class="rich-stack"><button id="ccEditArtifact" class="rich-btn">查看 / 微调代码</button></div>');
function artifact(role,title,html,css){infoCard(role,title,'Code · HTML / CSS','code',()=>{canvas($('#ccArtifactFrame'),html,css);artifactDialog.querySelector('h2').textContent=title;$('#ccEditArtifact').onclick=()=>{show(terminal);terminal.querySelector('details').open=true};show(artifactDialog)})}
function terminalCard(role){const root=el('div','cc-terminal-card'),head=el('div','cc-terminal-head'),title=el('strong','','小终端 · 草稿会话'),expand=mediaButton('展开终端和代码','expand',()=>show(terminal));head.append(title,expand);const output=el('pre','cc-terminal-output',lines.join('\n')),foot=el('div','cc-terminal-files');foot.append(el('span','','draft.html'),el('span','','draft.css'));root.append(head,el('small','cc-caption','本机展示 · 未连接 Termux'),output,foot);const row=el('div','rich-stack');row.append(btn('展开编辑',()=>{show(terminal);terminal.querySelector('details').open=true}),btn('收起输出',()=>{output.hidden=!output.hidden;row.lastElementChild.textContent=output.hidden?'展开输出':'收起输出'}));root.append(row);terminalViews.push(output);nativeMessage(role,root);return root}
function updateTerminalCards(){terminalViews.forEach(p=>{p.textContent=lines.join('\n');p.scrollTop=p.scrollHeight})}
// Countdown is a foreground preview backed by an absolute deadline, not a cron service.
const TIMERKEY='chaosheng-countdown-message-preview-v1';let countdown={status:'idle',title:'休息一下，喝口水',due:0,duration:120};try{const v=JSON.parse(localStorage.getItem(TIMERKEY));if(v&&['idle','running','done','cancelled'].includes(v.status)&&Number.isFinite(v.due)&&Number.isFinite(v.duration)&&v.duration>0&&v.duration<=86400&&typeof v.title==='string')countdown=v}catch{}
const timerNodes=[],timerDock=el('aside','cc-countdown-dock');timerDock.setAttribute('aria-label','倒计时悬浮卡');timerDock.innerHTML='<button class="cc-timer-tab" id="ccTimerTab" aria-expanded="false"><span>倒计时</span><strong id="ccMiniTime">02:00</strong></button><section id="ccTimerPanel" hidden><div class="rich-head"><strong>声声的小提醒</strong><button class="rich-btn" id="ccFoldTimer">收起</button></div><p id="ccTimerTitle"></p><div class="cc-countdown-number" id="ccBigTime"></div><progress id="ccTimerProgress" max="1" value="0"></progress><p class="cc-caption" id="ccTimerState"></p><div class="rich-stack" id="ccTimerActions"></div><p class="cc-caption">左滑完成 · 长按取消</p></section>';document.body.append(timerDock);
function saveTimer(){try{localStorage.setItem(TIMERKEY,JSON.stringify(countdown))}catch{hint('本次倒计时有效，但未能保存')}}
function timerText(now=Date.now()){if(countdown.status==='done')return '已完成';if(countdown.status==='cancelled')return '已取消';if(countdown.status==='idle')return fmt(countdown.duration);const diff=countdown.due-now;return diff>=0?fmt(Math.ceil(diff/1000)):'+'+fmt(Math.floor(-diff/1000))}
function paintTimer(){const active=countdown.status==='running',overtime=active&&Date.now()>countdown.due;timerDock.hidden=!active;timerDock.classList.toggle('overtime',overtime);$('#ccMiniTime').textContent=timerText();$('#ccBigTime').textContent=timerText();$('#ccTimerTitle').textContent=countdown.title;$('#ccTimerProgress').value=active?Math.max(0,Math.min(1,1-(countdown.due-Date.now())/(countdown.duration*1000))):0;$('#ccTimerState').textContent=overtime?'已超时 · 还在等你完成':'页面内倒计时 · 不会发送后台通知';for(const n of timerNodes){n.time.textContent=timerText();n.status.textContent=countdown.status==='idle'?'倒计时预览 · 点开始':countdown.status==='running'?(overtime?'已超时':'还剩'):(countdown.status==='done'?'做完了，记下啦。':'已取消，可重新开始');n.root.classList.toggle('overtime',overtime);n.action.textContent=active?'展开计时':'开始两分钟';n.finish.hidden=!active}}
function setTimerStatus(status){countdown.status=status;saveTimer();paintTimer();expandTimer(false)}
function startTimer(){countdown.due=Date.now()+countdown.duration*1000;countdown.status='running';saveTimer();paintTimer()}
function expandTimer(on){$('#ccTimerPanel').hidden=!on;$('#ccTimerTab').hidden=on;$('#ccTimerTab').setAttribute('aria-expanded',String(on));if(on)pin.hidden=true;else renderPin()}
$('#ccTimerTab').onclick=()=>expandTimer(true);$('#ccFoldTimer').onclick=()=>expandTimer(false);$('#ccTimerActions').append(btn('完成',()=>setTimerStatus('done'),'rich-btn alt'),btn('取消',()=>setTimerStatus('cancelled')));
let pointerStart=null,holdTimer;$('#ccTimerPanel').addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;pointerStart={x:e.clientX,y:e.clientY};holdTimer=setTimeout(()=>{setTimerStatus('cancelled');pointerStart=null},750)});$('#ccTimerPanel').addEventListener('pointermove',e=>{if(pointerStart&&Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y)>12)clearTimeout(holdTimer)});document.addEventListener('pointerup',e=>{clearTimeout(holdTimer);if(pointerStart&&e.clientX-pointerStart.x < -60&&Math.abs(e.clientY-pointerStart.y)<45)setTimerStatus('done');pointerStart=null});document.addEventListener('pointercancel',()=>{clearTimeout(holdTimer);pointerStart=null});
function timerCard(role){const root=el('div','cc-timer-card'),header=el('small','cc-caption','倒计时 · 声声的提醒'),title=el('strong','',countdown.title),time=el('div','cc-countdown-number'),status=el('small','cc-caption'),actions=el('div','rich-stack'),action=btn('开始两分钟',()=>{if(countdown.status!=='running')startTimer();expandTimer(true)}),finish=btn('完成',()=>setTimerStatus('done'),'rich-btn alt');actions.append(action,finish);root.append(header,title,time,status,actions);timerNodes.push({root,time,status,action,finish});nativeMessage(role,root);paintTimer()}
function reminderCard(role,text){const root=el('div','cc-reminder-card');root.append(el('small','cc-caption','声声的提醒'),el('strong','',text));const status=el('small','cc-caption','可以贴在旁边，等忙完再确认。'),actions=el('div','rich-stack');actions.append(btn('贴在旁边',()=>{remind(text);state.reminder.mini=true;persist();renderPin();status.textContent='提醒已经贴在聊天旁边。'}),btn('知道啦',()=>{if(state.reminder?.text===text){state.reminder=null;persist();renderPin()}status.textContent='已确认';actions.hidden=true},'rich-btn alt'));root.append(status,actions);nativeMessage(role,root)}
const imageDialog=dialog('ccImage','看看这张图','<img id="ccLargeImage" class="cc-large-image" alt=""><div id="ccImageActions"></div>');
function galleryCard(role,src,title){if(!url(src))return;const root=el('div','cc-gallery'),image=el('img');image.src=src;image.alt=title;image.loading='lazy';function view(){$('#ccLargeImage').src=src;$('#ccLargeImage').alt=title;$('#ccImageActions').replaceChildren(btn('收藏到预览',()=>{try{localStorage.setItem('chaosheng-preview-saved-image',JSON.stringify({src,title}));infoCard('sheng','收藏了「'+title+'」','已保存到本机预览 · 尚未同步相册','image',view);imageDialog.close()}catch{hint('浏览器未能保存收藏')}}));show(imageDialog)}const open=btn('',view,'cc-gallery-open');open.append(image);root.append(open,el('div','cc-gallery-caption','来自小窝 · '+title));nativeMessage(role,root)}
function updateDockPosition(){document.documentElement.style.setProperty('--cc-composer-height',$('#composerWrap').getBoundingClientRect().height+'px')}if(window.ResizeObserver)new ResizeObserver(updateDockPosition).observe($('#composerWrap'));window.addEventListener('resize',updateDockPosition);updateDockPosition();
setInterval(()=>{mediaStates.forEach(updateMedia);paintTimer()},250);paintTimer();

const oldCommandSubmit=$('#richCommandForm').onsubmit;
$('#richCommandForm').onsubmit=e=>{oldCommandSubmit(e);updateTerminalCards()};
const oldDraftPreview=$('#richDraftPreview').onclick;
$('#richDraftPreview').onclick=()=>{oldDraftPreview();canvas($('#ccArtifactFrame'),state.draftHtml,state.draftCss);lines.push('草稿预览已更新 · draft.html / draft.css','只更新本机预览，没有执行命令或改动仓库。');lines=lines.slice(-100);log();updateTerminalCards()};
messages.append(el('p','cc-preview-label','以下是消息展示样例'));
markdown('这首歌想和你一起听。',bubble('sheng'));
const firstSpecial=messages.lastElementChild;
song('sheng','晚风来信','示例曲目 · 轻柔钢琴');
markdown('那我也给你分享一首 ouo',bubble('me'));
song('me','靠近一点','示例曲目 · 木吉他');
markdown('给你两分钟，去喝口水。',bubble('sheng'));
timerCard('sheng');
markdown('小改动在这里就能看，改完收起来。',bubble('sheng'));
terminalCard('sheng');
artifact('sheng','给你写了一张小纸条',state.draftHtml,state.draftCss);
infoCard('sheng','一起看看这个网页','example.com · 网页','link',()=>openWeb('https://example.com/'));
reminderCard('sheng','忙完记得休息一下，我在这里。');
markdown('也可以把小窝里收藏的图发给你。',bubble('sheng'));
galleryCard('sheng','https://files.catbox.moe/eyt5q8.png','猫头留言板');
voice('me','声声，听得到吗？');
voice('sheng','听得到，我在这里。');
markdown('**今天的小便签**\n\n> 慢慢来，我陪你。\n\n- [x] 把喜欢的歌分享给你\n- [ ] 一起听完\n\n| 留下的东西 | 放在哪里 |\n| --- | --- |\n| 喜欢的歌 | 唱片架 |\n| 小纸条 | 留言板 |',bubble('sheng'));
requestAnimationFrame(()=>messages.scrollTo({top:Math.max(0,firstSpecial.offsetTop-messages.offsetTop-16),behavior:'instant'}));

try{const shared=JSON.parse(sessionStorage.getItem('chaosheng-song-share-preview'));if(shared&&typeof shared.title==='string'){song('me',shared.title.slice(0,100),String(shared.artist||'').slice(0,100));sessionStorage.removeItem('chaosheng-song-share-preview')}}catch{}
// Use the same safe rich-text renderer for new user messages; never evaluate message code.
function sendRich(){const input=$('#input'),text=input.value.trim();if(!text)return hint('慢慢说…');if(url(text)){const u=url(text);card('me',new URL(u).hostname,u,()=>openWeb(u),'查看网页')}else markdown(text,bubble('me'));input.value='';resizeInput();window.__playSendMorph?.()}
$('#send').onclick=sendRich;$('#input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();sendRich()}};
// Future structured-message adapter. Only explicit typed cards; no terminal execution bridge.
window.ChatSpecialPreview={appendMessage(message){if(!message||typeof message!=='object')return;const role=message.role==='me'?'me':'sheng';switch(message.type){
case 'song':return song(role,String(message.title||'分享一首歌'),String(message.artist||''));
case 'voice':return voice(role,String(message.text||'语音文字'));
case 'web':{const u=url(message.url);if(u)return infoCard(role,String(message.title||new URL(u).hostname),u,'link',()=>openWeb(u));break}
case 'html':return artifact(role,String(message.title||'HTML 作品'),String(message.html||''),String(message.css||''));
case 'image':return galleryCard(role,String(message.url||''),String(message.title||'图片'));
case 'reminder':reminderCard(role,String(message.text||'记得休息一下'));remind(String(message.text||'记得休息一下'));state.reminder.mini=true;persist();renderPin();break;
case 'terminal':return terminalCard(role);
case 'timer':countdown.title=String(message.text||'休息一下');countdown.duration=Number.isFinite(message.seconds)&&message.seconds>0?Math.min(86400,Math.floor(message.seconds)):120;startTimer();return timerCard(role);
case 'cron':return infoCard(role,String(message.title||'定时任务'),String(message.text||'定时任务草稿 · 待接入'),'clock',()=>{renderTasks();show(tasksDialog)});
default:return markdown(String(message.text||''),bubble(role))
}},openTerminal:()=>show(terminal)};
})();
