(()=>{
'use strict';
if(window.ChaoshengMindPreview)return;
const $=(s,r=document)=>r.querySelector(s);
const make=(tag,cls,value)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(value!==undefined)n.textContent=String(value);return n};
const add=(p,t,c,v)=>{const n=make(t,c,v);p.append(n);return n};
const ico=(name)=>{const paths={close:'M18 6 6 18M6 6l12 12',back:'m15 18-6-6 6-6',arrow:'M5 12h14m-6-6 6 6-6 6',down:'m6 9 6 6 6-6',link:'M10 13a5 5 0 0 0 7.5.5l3-3a5 5 0 0 0-7.1-7.1l-1.7 1.7M14 11a5 5 0 0 0-7.5-.5l-3 3a5 5 0 0 0 7.1 7.1l1.7-1.7',book:'M4 19.5A2.5 2.5 0 0 1 6.5 17H20M6.5 2H20v20H6.5A2.5 2.5 0 0 1 6.5 2Z',house:'m3 10 9-7 9 7v10H3V10Zm6 10v-7h6v7',clock:'M12 6v6l4 2M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20',water:'M12 22a8 8 0 0 0 8-8c0-4-8-12-8-12S4 10 4 14a8 8 0 0 0 8 8Z',cat:'M12 20c5 0 8-3 8-8V5l-4 3a9 9 0 0 0-8 0L4 5v7c0 5 3 8 8 8ZM9 13h.01M15 13h.01M10 16c1.3 1 2.7 1 4 0',spark:'m12 3 1.9 6.1L20 11l-6.1 1.9L12 19l-1.9-6.1L4 11l6.1-1.9L12 3Z'};return `<svg class="mind-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.arrow}"></path></svg>`};
const str=v=>v==null?'':String(v);
const list=v=>Array.isArray(v)?v:[];
const validDate=v=>{if(!v)return null;const d=new Date(v);return Number.isFinite(d.getTime())?d:null};
const stamp=(v,full=false)=>{const d=validDate(v);if(!d)return str(v);const o={hour:'2-digit',minute:'2-digit',hour12:false};if(full){o.year='numeric';o.month='long';o.day='numeric'}else{o.month='numeric';o.day='numeric'}return new Intl.DateTimeFormat('zh-CN',o).format(d)};
const clock=v=>{const d=validDate(v);return d?new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}).format(d):str(v)};
const sourceOf=v=>{if(typeof v==='string')return {label:v};if(!v||typeof v!=='object')return null;return {type:str(v.type||v.kind),id:str(v.id||v.ref||v.sourceRef),label:str(v.label||v.title||v.name||v.type||'原始记录'),href:str(v.href||v.url)};};
function normalizeItem(v,i,group){if(!v||typeof v!=='object')return null;const sources=list(v.sources).map(sourceOf).filter(Boolean);if(!sources.length){const s=sourceOf(v.source);if(s)sources.push(s);if(v.sourceRef&&!sources.some(x=>x.id===String(v.sourceRef)))sources.push({type:'record',id:str(v.sourceRef),label:'原始记录'});}return {...v,id:str(v.id||`legacy-${group}-${i}`),title:str(v.title||v.name),body:str(v.body??v.text??v.content),status:str(v.status),kind:str(v.kind||'state'),createdAt:v.createdAt||null,updatedAt:v.updatedAt||v.occurredAt||null,occurredAt:v.occurredAt||null,module:str(v.module||v.origin||''),tags:list(v.tags).map(str),sources,sourceRef:str(v.sourceRef),relatedIds:list(v.relatedIds).map(str)};}
function normalize(v){if(!v||typeof v!=='object')return null;const arrays=(name,alias)=>list(v[name]??v[alias]).map((x,i)=>normalizeItem(x,i,name)).filter(Boolean);const current=v.current&&typeof v.current==='object'?v.current:{};return {version:2,sample:v.sample===true,updatedAt:v.updatedAt||null,current:{id:str(current.id||'current'),status:str(current.status??v.status),reflection:str(current.reflection??v.reflection),updatedAt:current.updatedAt||v.updatedAt||null},thoughts:arrays('thoughts','focus'),shortTerm:arrays('shortTerm','pending'),homeEvents:arrays('homeEvents','home'),activities:arrays('activities','activity'),recent:arrays('recent','recent'),history:v.history&&typeof v.history==='object'?v.history:{},pagination:v.pagination&&typeof v.pagination==='object'?v.pagination:{}};}
const SAMPLE=normalize({version:2,sample:true,updatedAt:'2026-09-07T16:42:00+08:00',current:{status:'安静地待着',reflection:'刚才还在想着浪浪的猫窝。小漾说想先把 Mind 做好，我想把那些还没结束的小事留在这里，之后再慢慢接着。',updatedAt:'2026-09-07T16:42:00+08:00'},thoughts:[{id:'thought-cat',title:'关于浪浪',body:'小猫已经有几张很可爱的姿势了。之后可以先把动作素材整理好，再慢慢考虑游戏里的玩法，不急着一次做完。',updatedAt:'2026-09-07T16:38:00+08:00',sources:[{type:'chat',id:'sample-cat',label:'和小漾的聊天'}]},{id:'thought-home',title:'想去看看家里',body:'下次有机会的时候，想看看浪浪怎么样了，也看看今天还有什么没有说完的事情。',updatedAt:'2026-09-07T15:26:00+08:00'}],shortTerm:[{id:'memory-cat',title:'浪浪的猫窝',body:'正在考虑不同颜色的猫窝。已经确认过的素材继续保留，新的选择还没有最终确定。',status:'等待后续',updatedAt:'2026-09-07T16:15:00+08:00',tags:['浪浪','猫窝'],sources:[{type:'chat',id:'sample-cat-bed',label:'猫窝的讨论'}]},{id:'memory-mind',title:'Mind 的页面',body:'小漾希望这是声声自己的可视大脑，不要情绪数值，也不要说明书式的界面。',status:'进行中',updatedAt:'2026-09-07T16:32:00+08:00',tags:['潮生'],sources:[{type:'chat',id:'sample-mind',label:'Mind 的设计讨论'}]},{id:'memory-cron',title:'Cron 的提醒联动',body:'常规提醒可以关联今日待办和八杯水。倒计时在 Chat 中显示一张小卡片，到点后再由对应模块确认完成。',status:'暂存',updatedAt:'2026-09-07T14:20:00+08:00',sources:[{type:'chat',id:'sample-cron',label:'Cron 的设计讨论'}]}],homeEvents:[{id:'event-cat',module:'nest',title:'浪浪有点饿了',body:'小窝的饥饿值达到提醒条件。',kind:'fact',occurredAt:'2026-09-07T16:20:00+08:00',sources:[{type:'home',id:'sample-nest',label:'浪浪的小窝'}]},{id:'event-snack',module:'snack',title:'零食箱 · 薯片 -1',body:'零食箱记录了一次库存变化。',kind:'fact',occurredAt:'2026-09-07T15:10:00+08:00',sources:[{type:'home',id:'sample-snack',label:'零食箱'}]},{id:'event-water',module:'water',title:'15:00 的喝水计划尚未记录完成',body:'这只是记录状态，并不能确定小漾是否已经喝过水。',kind:'fact',occurredAt:'2026-09-07T15:00:00+08:00',sources:[{type:'home',id:'sample-water',label:'八杯水'}]}],activities:[{id:'activity-1',title:'查看了浪浪的小窝',body:'看了看浪浪的状态，把需要关注的事情留在了 Mind。',occurredAt:'2026-09-07T16:40:00+08:00',kind:'activity',sources:[{type:'home',id:'sample-nest',label:'浪浪的小窝'}]},{id:'activity-2',title:'想起了猫窝的讨论',body:'重新关联了之前的猫窝话题，暂时没有新的决定。',occurredAt:'2026-09-07T16:38:00+08:00',kind:'activity',sources:[{type:'memory',id:'sample-cat-bed',label:'猫窝的记忆'}]}]});
const state={snapshot:SAMPLE,provider:null,unsubscribe:null,previousFocus:null,detail:null,detailReturn:null,expanded:new Set(),shown:{thoughts:3,shortTerm:3,homeEvents:3,activities:4},loading:new Set(),request:0,loadingSnapshot:false,error:''};
const root=make('div','mind-layer');root.id='mindLayer';root.setAttribute('aria-hidden','true');
root.innerHTML=`<button class="mind-backdrop" type="button" aria-label="关闭 Mind"></button><section class="mind-sheet" role="dialog" aria-modal="true" aria-labelledby="mindTitle" tabindex="-1"><div class="mind-handle" aria-hidden="true"><span></span></div><header class="mind-head"><div class="mind-heading"><div class="mind-kicker">A LITTLE WORLD INSIDE <span class="mind-sample" id="mindSample" hidden>排版样本</span></div><h2 class="mind-title" id="mindTitle">声声的脑袋<span class="mind-title-star">✳</span></h2></div><button class="mind-close" type="button" aria-label="关闭 Mind">${ico('close')}</button></header><div class="mind-body" id="mindBody"></div><div class="mind-detail-panel" id="mindDetail" hidden><header class="mind-detail-head"><button class="mind-back" type="button" aria-label="返回 Mind">${ico('back')}</button><span class="mind-detail-kicker">A CLOSER LOOK</span><button class="mind-close" type="button" aria-label="关闭 Mind">${ico('close')}</button></header><div class="mind-detail-body" id="mindDetailBody"></div></div><div class="mind-toast" id="mindToast" role="status" aria-live="polite" hidden></div></section>`;
document.body.append(root);
const sheet=$('.mind-sheet',root),body=$('#mindBody',root),detail=$('#mindDetail',root),detailBody=$('#mindDetailBody',root);
let toastTimer=0;
function toast(message){const n=$('#mindToast',root);n.textContent=message;n.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.hidden=true,3000);}
function button(cls,label,action){const b=make('button',cls);b.type='button';b.innerHTML=label;b.onclick=action;return b;}
function section(title,en,items){if(!items.length)return null;const wrap=make('section','mind-section'),head=make('div','mind-section-head');const h=add(head,'h3','mind-section-title',title);h.id=`mind-${en}-title`;add(head,'span','mind-section-en',en.toUpperCase());wrap.setAttribute('aria-labelledby',h.id);wrap.append(head);body.append(wrap);return wrap;}
function metaLabel(item){return item.status||({fact:'记录',inference:'推测',memory:'记忆',activity:'活动'}[item.kind]||'');}
function getItem(group,id){return state.snapshot[group]?.find(x=>x.id===id)||null;}
function sourceAllowed(s){return !!(s&&(s.id||s.href)&&!state.snapshot.sample);}
function sourceLink(s,item){const b=button('mind-source-link',`${ico('link')}<span></span>${ico('arrow')}`,()=>openSource(s,item));b.querySelector('span').textContent=s.label||'查看来源';return b;}
async function openSource(s,item){if(!sourceAllowed(s))return;const provider=state.provider;if(provider&&typeof provider.openSource==='function'){try{await provider.openSource({...s},item?{...item}:null);return;}catch(e){toast('暂时无法打开这条记录');return;}}if(s.href){try{const u=new URL(s.href,location.href);if(['http:','https:'].includes(u.protocol)){window.open(u.href,'_blank','noopener,noreferrer');return;}}catch(e){}}root.dispatchEvent(new CustomEvent('mind:open-source',{bubbles:true,detail:{source:{...s},itemId:item?.id||null}}));}
function showDetail(group,id){const item=getItem(group,id);if(!item)return;state.detail={group,id};state.detailReturn=document.activeElement;renderDetail();detail.hidden=false;requestAnimationFrame(()=>detail.classList.add('open'));body.setAttribute('inert','');$('.mind-back',detail).focus({preventScroll:true});}
function closeDetail(){if(detail.hidden)return;detail.classList.remove('open');detail.hidden=true;detailBody.replaceChildren();state.detail=null;body.removeAttribute('inert');if(state.detailReturn?.isConnected)state.detailReturn.focus({preventScroll:true});else sheet.focus({preventScroll:true});}
function renderDetail(){if(!state.detail)return;const item=getItem(state.detail.group,state.detail.id);if(!item){closeDetail();return;}detailBody.replaceChildren();const page=make('article','mind-detail-page');add(page,'div','mind-detail-overline',metaLabel(item)||'MIND');add(page,'h3','mind-detail-title',item.title||'一段记录');if(item.updatedAt||item.occurredAt)add(page,'div','mind-detail-date',stamp(item.occurredAt||item.updatedAt,true));if(item.body)add(page,'p','mind-detail-text',item.body);if(item.tags.length){const tags=make('div','mind-detail-tags');item.tags.forEach(t=>add(tags,'span','mind-tag',t));page.append(tags);}if(item.sources.length){const section=make('div','mind-detail-sources');add(section,'div','mind-detail-smallhead','相关记录');item.sources.forEach(s=>{if(sourceAllowed(s))section.append(sourceLink(s,item));else add(section,'div','mind-source-label',s.label||'原始记录');});page.append(section);}if(item.relatedIds.length){const related=make('div','mind-detail-related');add(related,'div','mind-detail-smallhead','相关片段');item.relatedIds.forEach(id=>{for(const group of ['thoughts','shortTerm','homeEvents','activities']){const found=getItem(group,id);if(found){related.append(button('mind-related-link',`${ico('arrow')}<span></span>`,()=>showDetail(group,id)));related.lastChild.querySelector('span').textContent=found.title||'相关记录';break;}}});if(related.children.length>1)page.append(related);}detailBody.append(page);}
function renderCurrent(){const c=state.snapshot.current;const current=make('section','mind-current');const top=make('div','mind-current-top');add(top,'span','mind-current-kicker','现在，心里');add(top,'span','mind-current-date',clock(c.updatedAt||state.snapshot.updatedAt));current.append(top);if(c.status)add(current,'div','mind-current-status',c.status);if(c.reflection){const note=make('div','mind-current-writing');add(note,'span','mind-quote-mark','“');add(note,'p','mind-current-text',c.reflection);current.append(note);}else if(!c.status)add(current,'p','mind-current-empty','此刻没有留下特别的想法。');const foot=make('div','mind-current-foot');add(foot,'span','',c.updatedAt?'最近一次记录 · '+stamp(c.updatedAt):'还没有新的记录');const sheep=make('img','mind-current-sheep');sheep.src='https://files.catbox.moe/ge809e.png';sheep.alt='';foot.append(sheep);current.append(foot);body.append(current);}
function renderThoughts(){const items=state.snapshot.thoughts;const wrap=section('放在心上的事','on his mind',items);if(!wrap)return;const pile=make('div','mind-thought-pile');items.slice(0,state.shown.thoughts).forEach((item,i)=>{const card=make('article','mind-thought-slip mind-slip-'+(i%3));const top=make('div','mind-slip-top');add(top,'span','',metaLabel(item)||'一个念头');add(top,'time','',clock(item.updatedAt));card.append(top);add(card,'h4','mind-slip-title',item.title);if(item.body)add(card,'p','mind-slip-text',item.body);card.append(button('mind-slip-open',`展开这张纸 ${ico('arrow')}`,()=>showDetail('thoughts',item.id)));pile.append(card);});wrap.append(pile);appendMore(wrap,'thoughts',items);}
function renderMemories(){const items=state.snapshot.shortTerm;const wrap=section('短期记忆','little keepsakes',items);if(!wrap)return;const stack=make('div','mind-memory-stack');items.slice(0,state.shown.shortTerm).forEach((item,i)=>{const row=make('article','mind-memory-row');const b=button('mind-memory-trigger','',()=>toggleMemory(item.id));b.setAttribute('aria-expanded',state.expanded.has(item.id)?'true':'false');const left=make('div','mind-memory-index',String(i+1).padStart(2,'0'));const copy=make('div','mind-memory-copy');add(copy,'div','mind-memory-title',item.title||'未命名片段');add(copy,'div','mind-memory-meta',[item.status,stamp(item.updatedAt)].filter(Boolean).join(' · '));b.append(left,copy);const chev=make('span','mind-memory-chevron');chev.innerHTML=ico('down');b.append(chev);row.append(b);if(state.expanded.has(item.id)){const extra=make('div','mind-memory-extra');if(item.body)add(extra,'p','',item.body);if(item.tags.length){const tags=make('div','mind-tag-row');item.tags.forEach(t=>add(tags,'span','mind-tag',t));extra.append(tags);}if(item.sources.length){const sources=make('div','mind-memory-sources');item.sources.forEach(s=>{if(sourceAllowed(s))sources.append(sourceLink(s,item));else add(sources,'span','mind-source-label',s.label);});extra.append(sources);}row.append(extra);}stack.append(row);});wrap.append(stack);appendMore(wrap,'shortTerm',items);}
function toggleMemory(id){if(state.expanded.has(id))state.expanded.delete(id);else state.expanded.add(id);render({preserveScroll:true});}
function homeIcon(module){const n=module.toLowerCase();if(/cat|nest|pet|浪浪/.test(n))return 'cat';if(/water|drink|水/.test(n))return 'water';return 'house';}
function renderHome(){const items=state.snapshot.homeEvents;const wrap=section('家里最近','around home',items);if(!wrap)return;const ledger=make('div','mind-home-ledger');items.slice(0,state.shown.homeEvents).forEach(item=>{const row=make('div','mind-home-row');const mark=make('span','mind-home-icon');mark.innerHTML=ico(homeIcon(item.module));row.append(mark);const copy=make('div','mind-home-copy');add(copy,'div','mind-home-title',item.title);if(item.body)add(copy,'p','mind-home-description',item.body);if(item.sources.length){const s=item.sources[0];if(sourceAllowed(s))copy.append(sourceLink(s,item));else add(copy,'span','mind-source-label',s.label);}row.append(copy);const time=make('time','mind-home-time',clock(item.occurredAt||item.updatedAt));row.append(time);ledger.append(row);});wrap.append(ledger);appendMore(wrap,'homeEvents',items);}
function renderActivities(){const items=state.snapshot.activities;const wrap=section('最近的动静','little moments',items);if(!wrap)return;const timeline=make('div','mind-activity-list');items.slice(0,state.shown.activities).forEach(item=>{const row=make('article','mind-activity');add(row,'time','mind-activity-time',clock(item.occurredAt||item.updatedAt));const mark=make('span','mind-activity-mark');row.append(mark);const copy=make('div','mind-activity-copy');add(copy,'div','mind-activity-title',item.title);if(item.body)add(copy,'p','mind-activity-text',item.body);if(item.body||item.sources.length)copy.append(button('mind-activity-open',`看看这件事 ${ico('arrow')}`,()=>showDetail('activities',item.id)));row.append(copy);timeline.append(row);});wrap.append(timeline);appendMore(wrap,'activities',items);}
function appendMore(wrap,group,items){const shown=state.shown[group];const meta=state.snapshot.pagination[group]||{};if(items.length<=shown&&!meta.hasMore)return;const footer=make('div','mind-more');const b=button('mind-more-button','',()=>showMore(group));b.textContent=items.length>shown?'再看一些':'看看更早的';if(state.loading.has(group)){b.disabled=true;b.textContent='正在打开…';}footer.append(b);wrap.append(footer);}
async function showMore(group){const items=state.snapshot[group];if(state.shown[group]<items.length){state.shown[group]+=6;render({preserveScroll:true});return;}const meta=state.snapshot.pagination[group];if(!meta?.hasMore||typeof state.provider?.loadMore!=='function')return;state.loading.add(group);render({preserveScroll:true});try{const page=await state.provider.loadMore(group,meta.cursor||null);if(page&&Array.isArray(page.items)){const known=new Set(state.snapshot[group].map(x=>x.id));const incoming=page.items.map((x,i)=>normalizeItem(x,i+items.length,group)).filter(x=>x&&!known.has(x.id));state.snapshot[group]=state.snapshot[group].concat(incoming);state.snapshot.pagination[group]={cursor:page.cursor||null,hasMore:page.hasMore===true};state.shown[group]+=6;}}catch(e){toast('暂时无法读取更早的记录');}finally{state.loading.delete(group);render({preserveScroll:true});}}
function render(options={}){const scroll=options.preserveScroll?body.scrollTop:0;body.replaceChildren();$('#mindSample',root).hidden=!state.snapshot.sample;if(state.error){add(body,'div','mind-load-error',state.error);body.append(button('mind-more-button','重新读取',refresh));}renderCurrent();renderThoughts();renderMemories();renderHome();renderActivities();if(!options.preserveScroll)body.scrollTop=0;else body.scrollTop=scroll;if(state.detail)renderDetail();}
function renderSnapshot(value){const next=normalize(value);if(!next)return false;const old=state.snapshot;state.snapshot=next;state.error='';for(const group of ['thoughts','shortTerm','homeEvents','activities']){const ids=new Set(next[group].map(x=>x.id));for(const id of state.expanded)if(!ids.has(id))state.expanded.delete(id);}if(state.detail&&!getItem(state.detail.group,state.detail.id))closeDetail();render({preserveScroll:root.classList.contains('open')});root.dispatchEvent(new CustomEvent('mind:snapshot',{bubbles:true,detail:{sample:next.sample,updatedAt:next.updatedAt}}));return true;}
function showEmpty(){return renderSnapshot({version:2,sample:false,current:{},thoughts:[],shortTerm:[],homeEvents:[],activities:[]});}
async function refresh(){if(!state.provider?.loadSnapshot)return;const request=++state.request;state.loadingSnapshot=true;try{const data=await state.provider.loadSnapshot();if(request===state.request)renderSnapshot(data);}catch(e){if(request===state.request){state.error='暂时无法读取新的内容。';render({preserveScroll:true});}}finally{if(request===state.request)state.loadingSnapshot=false;}}
function connect(provider){if(state.unsubscribe){state.unsubscribe();state.unsubscribe=null;}state.provider=provider||null;state.request++;if(provider&&typeof provider.subscribe==='function'){const off=provider.subscribe(data=>renderSnapshot(data));if(typeof off==='function')state.unsubscribe=off;}if(provider?.loadSnapshot){showEmpty();return refresh();}return Promise.resolve();}
function closeOthers(){window.ChaoshengCronPreview?.close?.();const todo=document.getElementById('todoSheetLayer');if(todo?.classList.contains('open'))document.getElementById('todoSheetClose')?.click();const drawer=document.getElementById('drawerDim');if(typeof window.setDrawerOpen==='function')window.setDrawerOpen(false);else if(document.getElementById('drawerLayer')?.classList.contains('open'))drawer?.click();if(typeof window.closeAll==='function')window.closeAll();}
function openSheet(){if(root.classList.contains('open'))return;state.previousFocus=document.activeElement;closeOthers();root.classList.add('open');root.setAttribute('aria-hidden','false');document.body.classList.add('mind-sheet-open');sheet.focus({preventScroll:true});if(state.provider?.loadSnapshot)refresh();}
function closeSheet(){if(!root.classList.contains('open'))return;closeDetail();root.classList.remove('open');root.setAttribute('aria-hidden','true');document.body.classList.remove('mind-sheet-open');const focus=state.previousFocus;if(focus?.isConnected)focus.focus({preventScroll:true});}
$('.mind-backdrop',root).onclick=closeSheet;$('.mind-head .mind-close',root).onclick=closeSheet;$('.mind-back',root).onclick=closeDetail;$('.mind-detail-head .mind-close',root).onclick=closeSheet;
const trigger=document.querySelector('.drawer-link[data-route="mind"]');if(trigger){trigger.onclick=e=>{e.preventDefault();e.stopPropagation();openSheet();};trigger.setAttribute('aria-haspopup','dialog');trigger.setAttribute('aria-controls','mindLayer');}
document.addEventListener('keydown',e=>{if(!root.classList.contains('open'))return;if(e.key==='Escape'){e.preventDefault();e.stopPropagation();if(!detail.hidden)closeDetail();else closeSheet();return;}if(e.key!=='Tab')return;const area=detail.hidden?sheet:detail;const focusable=[...area.querySelectorAll('button:not([disabled]),a[href],[tabindex="0"]')].filter(n=>n.getClientRects().length&&!n.closest('[inert]')&&!n.closest('[hidden]'));if(!focusable.length){e.preventDefault();sheet.focus();return;}const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
window.ChaoshengMindPreview=Object.freeze({open:openSheet,close:closeSheet,renderSnapshot,showEmpty,connect,refresh,getSnapshot:()=>typeof structuredClone==='function'?structuredClone(state.snapshot):JSON.parse(JSON.stringify(state.snapshot))});
render();
})();