(()=>{
'use strict';
if(window.ChaoshengMindPreview)return;
const $=(s,r=document)=>r.querySelector(s);
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
const icon=(name)=>{const paths={close:'M18 6 6 18M6 6l12 12',back:'m15 18-6-6 6-6',arrow:'M5 12h14m-6-6 6 6-6 6',link:'M10 13a5 5 0 0 0 7.5.5l3-3a5 5 0 0 0-7.1-7.1l-1.7 1.7M14 11a5 5 0 0 0-7.5-.5l-3 3a5 5 0 0 0 7.1 7.1l1.7-1.7'};return `<svg class="mind-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.arrow}"></path></svg>`};
const text=(value,max=1200)=>String(value??'').slice(0,max);
const SAMPLE={sample:true,updatedAt:'演示资料 · 非实时',status:'正在整理一些想法',reflection:'今天想把关于浪浪的小事慢慢理清楚。还有几件没做完的事，我先记在这里，不急着都说出来。',focus:[{id:'cat',title:'浪浪的动作与小窝',body:'动作素材还在逐步完善。先保留已有的母版和已确认的版本，之后再接着做。',status:'进行中',source:'示例 · 项目对话',kind:'state',tags:['浪浪','美术']},{id:'memory',title:'新记忆系统的约定',body:'关于已确认小记的修订、上下文满时的安全接续，还有需要继续商量的地方。',status:'待续',source:'示例 · 记忆系统讨论',kind:'state',tags:['记忆','待讨论']}],recent:[{id:'home',title:'关于 Home 的记录',body:'没有喝水记录，不等于小漾没有喝水。需要区分看见的事实和自己的猜测。',status:'示例观察',source:'示例 · Home 联动设计',kind:'fact',tags:['事实与推测']},{id:'context',title:'今天的上下文',body:'整理过的阶段记忆与尚未整理的原始聊天需要分开保留，避免重复或漏掉。',status:'示例记忆',source:'示例 · 记忆系统讨论',kind:'memory',tags:['上下文']}],pending:[{id:'later',title:'留着以后再接着说',body:'等我们把 Mind 的展示方式定下来，再继续讨论它怎样与真实的短期记忆和调度器连接。',status:'待续',source:'示例 · 当前设计讨论',kind:'state',tags:['Mind']} ]};
const state={snapshot:SAMPLE,detail:null,previousFocus:null};
const root=el('div','mind-layer');root.id='mindLayer';root.setAttribute('aria-hidden','true');
root.innerHTML=`<button class="mind-backdrop" type="button" aria-label="关闭 Mind"></button><section class="mind-sheet" role="dialog" aria-modal="true" aria-labelledby="mindTitle" tabindex="-1"><div class="mind-handle" aria-hidden="true"><span></span></div><header class="mind-head"><div><div class="mind-kicker"><i>✦</i> A LITTLE WINDOW INSIDE</div><h2 class="mind-title" id="mindTitle">声声的脑袋</h2><p class="mind-subtitle">Mind · 那些正在想着、还放在心上的事。</p></div><button class="mind-close" type="button" aria-label="关闭 Mind">${icon('close')}</button></header><div class="mind-body" id="mindBody"></div><div class="mind-detail-panel" id="mindDetail" hidden><header class="mind-detail-head"><button class="mind-back" type="button" aria-label="返回 Mind">${icon('back')}</button><h3 id="mindDetailTitle">详细内容</h3><button class="mind-close" type="button" aria-label="关闭详细内容">${icon('close')}</button></header><div class="mind-detail-body" id="mindDetailBody"></div></div></section>`;
document.body.append(root);
const sheet=$('.mind-sheet',root),body=$('#mindBody',root),detail=$('#mindDetail',root),detailBody=$('#mindDetailBody',root);
function addText(parent,tag,cls,value){const n=el(tag,cls,text(value));parent.append(n);return n}
function section(title,en){const wrap=el('section','mind-section'),head=el('div','mind-section-head');addText(head,'div','mind-section-title',title);addText(head,'div','mind-section-en',en);wrap.append(head);body.append(wrap);return wrap}
function sourceLabel(item){return item.source||'暂无来源信息'}
function normalizeItem(item,index){if(!item||typeof item!=='object')return null;return {id:text(item.id||`item-${index}`,100),title:text(item.title,180),body:text(item.body,2000),status:text(item.status,40),source:text(item.source,180),sourceRef:text(item.sourceRef,180),kind:['fact','inference','memory','state'].includes(item.kind)?item.kind:'state',tags:Array.isArray(item.tags)?item.tags.slice(0,6).map(v=>text(v,30)):[]}}
function normalize(value){if(!value||typeof value!=='object')return null;const array=name=>Array.isArray(value[name])?value[name].slice(0,30).map(normalizeItem).filter(Boolean):[];return {sample:value.sample===true,updatedAt:text(value.updatedAt,120),status:text(value.status,120),reflection:text(value.reflection,1600),focus:array('focus'),recent:array('recent'),pending:array('pending')}}
function findItem(id){for(const group of ['focus','recent','pending']){const item=state.snapshot[group].find(x=>x.id===id);if(item)return item}return null}
function renderCard(item,tinted=false){const card=el('article','mind-note'+(tinted?' mind-tinted':''));const top=el('div','mind-note-top');addText(top,'span','mind-note-label',item.status||'放在心上');addText(top,'span','mind-note-date',state.snapshot.sample?'示例':'Mind');card.append(top);addText(card,'div','mind-note-title',item.title);if(item.body)addText(card,'p','mind-note-text',item.body);if(item.tags.length){const tags=el('div','mind-tag-row');item.tags.forEach((tag,i)=>addText(tags,'span','mind-tag'+(i%3===1?' green':''),tag));card.append(tags)}const link=el('button','mind-link');link.type='button';link.innerHTML=`来源与详情 ${icon('arrow')}`;link.onclick=()=>showDetail(item.id);card.append(link);return card}
function renderGroup(title,en,items,tinted=false){const wrap=section(title,en);if(!items.length){addText(wrap,'div','mind-empty','暂时没有放在这里的内容。');return}items.forEach(item=>wrap.append(renderCard(item,tinted)))}
function render(){const s=state.snapshot;body.replaceChildren();addText(body,'p','mind-preview-note',s.sample?'布局示例 · 以下是示例文案，不是声声实际的 Mind 状态或思考记录。':'只读视图 · 展示已保存的 Mind 状态，不会因打开页面而唤醒模型。');const hero=el('section','mind-hero');const top=el('div','mind-hero-top');const img=el('img','mind-sheep');img.src='https://files.catbox.moe/ge809e.png';img.alt='';top.append(img);const copy=el('div','mind-hero-copy');addText(copy,'div','mind-hero-label','MIND · CURRENT');addText(copy,'div','mind-hero-name','此刻的声声');addText(copy,'div','mind-hero-state',s.status||'暂时没有状态记录');top.append(copy);hero.append(top);if(s.reflection)addText(hero,'p','mind-hero-quote',s.reflection);const foot=el('div','mind-hero-foot');addText(foot,'span','',s.updatedAt||'暂无更新时间');addText(foot,'span','',s.sample?'示例文字':'只读');hero.append(foot);body.append(hero);renderGroup('正在放在心上的事','ON HIS MIND',s.focus);renderGroup('最近记得的片段','RECENT THREADS',s.recent,true);renderGroup('留着以后再接着','TO BE CONTINUED',s.pending);const divider=el('div','mind-divider');body.append(divider);addText(body,'p','mind-small-print','这里以后只展示声声自己写下并保存的短期状态、关注与思绪。小漾可以阅读，不通过这个页面修改他的情绪或决定。原始对话与正式记忆仍由各自的系统保存。');const about=el('button','mind-link');about.type='button';about.innerHTML=`关于这个小窗口 ${icon('arrow')}`;about.onclick=showAbout;body.append(about)}
function openDetail(title,build){state.detail=true;$('#mindDetailTitle',root).textContent=title;detailBody.replaceChildren();build(detailBody);detail.hidden=false;requestAnimationFrame(()=>detail.classList.add('open'));$('.mind-back',detail).focus({preventScroll:true})}
function closeDetail(){if(detail.hidden)return;detail.classList.remove('open');detail.hidden=true;detailBody.replaceChildren();state.detail=null;sheet.focus({preventScroll:true})}
function showDetail(id){const item=findItem(id);if(!item)return;openDetail('来源与详情',box=>{addText(box,'div','mind-note-label',item.status||'Mind');addText(box,'h4','',item.title);addText(box,'p','',item.body);addText(box,'h4','','来源');addText(box,'p','',sourceLabel(item));if(item.sourceRef)addText(box,'p','',`记录引用：${item.sourceRef}`);if(state.snapshot.sample)addText(box,'p','mind-preview-note','这是一条示例资料，没有真实的原始对话链接。');addText(box,'h4','','记录类型');addText(box,'p','',({fact:'已记录的事实',inference:'需要区分的推测',memory:'短期记忆引用',state:'声声自己保存的状态'})[item.kind]);addText(box,'p','mind-small-print','正式接入后，来源引用可用于返回相应原始记录或正式记忆；不会在这里重新改写历史。')})}
function showAbout(){openDetail('关于 Mind',box=>{addText(box,'h4','','一个可以接续的内部状态');addText(box,'p','','Mind 用来保存声声当前的关注、短期记忆、意图、待续的话题与自己写下的状态。它不是整份聊天档案，也不替代正式记忆。');addText(box,'h4','','只读，不是控制面板');addText(box,'p','','小漾可以阅读已经保存、允许展示的内容。状态由声声在被调用时更新，页面不提供强制调整情绪、亲密度或主动联系意愿的按钮。');addText(box,'h4','','不展示隐藏推理');addText(box,'p','','这里展示的是供应用使用的、模型明确写下的状态与反思，不是模型未公开的内部推理过程，也不声称记录了真实的意识活动。');addText(box,'h4','','和 Cron 的关系');addText(box,'p','','调度器未来只提供唤醒机会。声声可以根据已授权的工具、Mind 与 Home 状态决定要做什么，也可以不联系小漾。可靠提醒仍由独立调度负责。');addText(box,'p','mind-small-print','当前仅为前端设计预览。真实状态存储、授权与后端读取尚未接入。')})}
function closeOthers(){window.ChaoshengCronPreview?.close?.();const todo=document.getElementById('todoSheetLayer');if(todo?.classList.contains('open'))document.getElementById('todoSheetClose')?.click();if(typeof window.setDrawerOpen==='function')window.setDrawerOpen(false);else document.getElementById('drawerDim')?.click();if(typeof window.closeAll==='function')window.closeAll()}
function openSheet(){if(root.classList.contains('open'))return;state.previousFocus=document.activeElement;closeOthers();render();root.classList.add('open');root.setAttribute('aria-hidden','false');sheet.focus({preventScroll:true})}
function closeSheet(){if(!root.classList.contains('open'))return;closeDetail();root.classList.remove('open');root.setAttribute('aria-hidden','true');state.previousFocus?.focus?.({preventScroll:true})}
$('.mind-backdrop',root).onclick=closeSheet;$('.mind-head .mind-close',root).onclick=closeSheet;$('.mind-back',root).onclick=closeDetail;$('.mind-detail-head .mind-close',root).onclick=closeDetail;
const trigger=document.querySelector('.drawer-link[data-route="mind"]');if(trigger){trigger.onclick=e=>{e.preventDefault();e.stopPropagation();openSheet()};trigger.setAttribute('aria-haspopup','dialog')}
document.addEventListener('keydown',e=>{if(!root.classList.contains('open'))return;if(e.key==='Escape'){e.preventDefault();e.stopPropagation();if(!detail.hidden)closeDetail();else closeSheet();return}if(e.key!=='Tab')return;const area=detail.hidden?sheet:detail;const focusable=[...area.querySelectorAll('button:not([disabled]),[tabindex="0"]')].filter(n=>n.getClientRects().length&&n.offsetParent!==null&&!n.closest('[hidden]'));if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
window.ChaoshengMindPreview=Object.freeze({open:openSheet,close:closeSheet,renderSnapshot(value){const next=normalize(value);if(!next)return false;state.snapshot=next;closeDetail();render();return true},showEmpty(){state.snapshot=normalize({sample:false,status:'暂时没有状态记录',updatedAt:'尚未接入',focus:[],recent:[],pending:[]});closeDetail();render()}});
state.snapshot=normalize(SAMPLE);render();
})();
