(()=>{
const STORE='chaosheng-drawer-todos-v1',ARCHIVE_STORE='chaosheng-todo-archive-v2';
const PALETTE=[
'rgba(241,194,205,.54)','rgba(247,210,216,.56)','rgba(239,208,163,.54)','rgba(246,224,180,.56)',
'rgba(218,228,181,.54)','rgba(199,222,199,.54)','rgba(190,224,213,.54)','rgba(196,223,229,.55)',
'rgba(194,216,238,.55)','rgba(210,208,235,.55)','rgba(221,202,235,.54)','rgba(232,202,222,.54)',
'rgba(239,210,199,.55)','rgba(242,201,177,.54)','rgba(211,225,201,.55)','rgba(201,226,213,.55)',
'rgba(231,216,194,.54)','rgba(225,207,195,.54)','rgba(240,207,221,.55)','rgba(207,220,238,.55)',
'rgba(224,213,236,.55)','rgba(207,228,225,.55)','rgba(242,220,202,.55)','rgba(215,224,205,.55)'
];
const $=s=>document.querySelector(s),pad=n=>String(n).padStart(2,'0');
const layer=$('#todoSheetLayer'),sheet=$('#todoSheet'),backdrop=$('#todoSheetBackdrop'),closeBtn=$('#todoSheetClose'),handle=$('#todoHandle'),drawerTodo=$('.drawer-todo'),drawerTodoList=$('#drawerTodoList');
const tapeList=$('#todoTapeList'),progressBar=$('#todoProgressBar'),progressCopy=$('#todoProgressCopy'),sheetDate=$('#todoSheetDate'),addBox=$('.todo-add'),addInput=$('#todoAddInput'),authorBtn=$('#todoAuthorBtn'),addBtn=$('#todoAddBtn'),archiveBox=$('#todoArchive'),archiveInner=$('#todoArchiveInner');
if(!layer||!sheet||!drawerTodo||!drawerTodoList)return;
let paintId=null,dragY=0,dragging=false,archiveBtn=null,addFab=null,lastDay='';
function readStore(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')||{}}catch(e){return {}}}
function writeStore(v){localStorage.setItem(STORE,JSON.stringify(v))}
function readArchive(){try{const v=JSON.parse(localStorage.getItem(ARCHIVE_STORE)||'[]');return Array.isArray(v)?v:[]}catch(e){return []}}
function writeArchive(v){localStorage.setItem(ARCHIVE_STORE,JSON.stringify(v))}
function dayKey(d=new Date()){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function prettyDate(d=new Date()){const w=['SUN','MON','TUE','WED','THU','FRI','SAT'][d.getDay()],m=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'][d.getMonth()];return `${w} · ${m} ${pad(d.getDate())}`}
function archiveDateLabel(key){const d=new Date(`${key}T12:00:00`),w=['SUN','MON','TUE','WED','THU','FRI','SAT'][d.getDay()];return {short:key.slice(5).replace('-','.'),week:w}}
function hash(s=''){let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return h}
function localTime(iso){if(!iso)return '';const d=new Date(iso);return `${pad(d.getHours())}:${pad(d.getMinutes())}`}
function defaults(){return [{id:'water',text:'今天喝水',done:false,creator:'小漾'},{id:'parcel',text:'下午拿快递',done:false,creator:'小漾'}]}
function normalizeTask(t,i,date){const id=t.id||`todo-${date}-${i}-${Date.now()}`;return {id,text:String(t.text||'待办'),done:!!t.done,creator:t.creator||'小漾',completedAt:t.completedAt||null,colorIndex:Number.isInteger(t.colorIndex)?t.colorIndex:hash(`${date}:${id}`)%PALETTE.length}}
function prepareToday(){const today=dayKey(),store=readStore(),archive=readArchive();let changed=false,archiveChanged=false;const keys=Object.keys(store).filter(k=>/^\d{4}-\d{2}-\d{2}$/.test(k)).sort();
for(const k of keys){if(k>=today)continue;const items=(store[k]||[]).map((t,i)=>normalizeTask(t,i,k));store[k]=items;for(const t of items){if(!t.done)continue;const akey=`${k}:${t.id}`;if(archive.some(a=>a.key===akey))continue;archive.push({key:akey,date:k,id:t.id,text:t.text,creator:t.creator||'小漾',completedAt:t.completedAt||`${k}T23:59:00`,colorIndex:t.colorIndex});archiveChanged=true}}
if(!store[today]){const prev=keys.filter(k=>k<today).pop(),source=prev?(store[prev]||[]):defaults();store[today]=source.map((t,i)=>{const n=normalizeTask(t,i,today);return {...n,done:false,completedAt:null,colorIndex:hash(`${today}:${n.id}:${i}`)%PALETTE.length}});changed=true}else{store[today]=store[today].map((t,i)=>normalizeTask(t,i,today));changed=true}
if(changed)writeStore(store);if(archiveChanged)writeArchive(archive);lastDay=today;return store[today]}
function getToday(){const store=readStore(),today=dayKey();return (store[today]||prepareToday()).map((t,i)=>normalizeTask(t,i,today))}
function saveToday(items){const store=readStore();store[dayKey()]=items;writeStore(store)}
function tapeColor(t){return PALETTE[(t.colorIndex||0)%PALETTE.length]}
function toggleTask(id){const items=getToday(),item=items.find(x=>x.id===id);if(!item)return;item.done=!item.done;if(item.done){item.completedAt=new Date().toISOString();paintId=id}else{item.completedAt=null;paintId=null}saveToday(items);renderAll()}
function renderSidebar(){const items=getToday();drawerTodoList.innerHTML='';items.forEach(item=>{const b=document.createElement('button');b.type='button';b.className='todo-item'+(item.done?' done':'');b.dataset.todoId=item.id;b.innerHTML='<span class="todo-box"></span><span class="todo-text"></span>';b.querySelector('.todo-box').textContent=item.done?'✓':'';b.querySelector('.todo-text').textContent=item.text;drawerTodoList.appendChild(b)})}
function renderSheet(){const items=getToday(),done=items.filter(x=>x.done).length,total=items.length;sheetDate.textContent=prettyDate();progressBar.style.width=total?`${done/total*100}%`:'0%';progressCopy.textContent=`${done} / ${total}`;tapeList.innerHTML='';if(!items.length)tapeList.innerHTML='<div class="todo-tape-empty">今天还没有贴上任何胶带。</div>';
items.forEach(item=>{const b=document.createElement('button');b.type='button';b.className='todo-tape'+(item.done?' done':'')+(paintId===item.id?' just-painted':'');b.dataset.todoId=item.id;b.style.setProperty('--tape-color',tapeColor(item));b.innerHTML='<div class="tape-main"><span class="tape-author-pill"></span><span class="tape-text"></span></div><div class="tape-meta"><span class="tape-time"></span></div>';const pill=b.querySelector('.tape-author-pill');pill.textContent=`${item.creator||'小漾'} add`;pill.classList.add(item.creator==='声声'?'sheng':'yang');b.querySelector('.tape-text').textContent=item.text;b.querySelector('.tape-time').textContent=item.done?(item.completedAt?`${localTime(item.completedAt)} done`:'done'):'';b.onclick=()=>toggleTask(item.id);tapeList.appendChild(b)});setTimeout(()=>paintId=null,900);renderArchive()}
function renderArchive(){const archive=readArchive().sort((a,b)=>(b.date+(b.completedAt||'')).localeCompare(a.date+(a.completedAt||'')));archiveInner.innerHTML='';if(!archive.length){archiveInner.innerHTML='<div class="todo-tape-empty" style="padding:14px 4px">还没有以前收好的彩色胶带。</div>';return}const groups=new Map();archive.slice(0,80).forEach(a=>{if(!groups.has(a.date))groups.set(a.date,[]);groups.get(a.date).push(a)});for(const [date,items] of groups){const sec=document.createElement('section');sec.className='archive-day';const label=document.createElement('div');label.className='archive-day-label';const info=archiveDateLabel(date);label.innerHTML='<strong></strong><span></span>';label.querySelector('strong').textContent=info.short;label.querySelector('span').textContent=info.week;sec.appendChild(label);items.forEach(a=>{const row=document.createElement('div');row.className='archive-strip';row.style.setProperty('--archive-color',PALETTE[(a.colorIndex||0)%PALETTE.length]);row.innerHTML='<span></span><small></small>';row.querySelector('span').textContent=a.text;row.querySelector('small').textContent=localTime(a.completedAt);sec.appendChild(row)});archiveInner.appendChild(sec)}}
function renderAll(){prepareToday();renderSidebar();renderSheet()}
function ensureUi(){if(!archiveBtn){const head=$('.todo-sheet-head'),actions=document.createElement('div');actions.className='todo-head-actions';archiveBtn=document.createElement('button');archiveBtn.type='button';archiveBtn.id='todoArchiveBtn';archiveBtn.className='todo-head-icon';archiveBtn.setAttribute('aria-label','以前完成的待办');archiveBtn.setAttribute('aria-expanded','false');archiveBtn.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path id="todoArchiveMorphPath" d="M4 7h16M5 7v13h14V7M9 11h6M3 4h18v3H3Z"></path></svg>';closeBtn.parentNode.insertBefore(actions,closeBtn);actions.appendChild(archiveBtn);actions.appendChild(closeBtn);archiveBtn.onclick=e=>{e.stopPropagation();setArchiveOpen(!archiveBox.classList.contains('open'))}}
if(!archiveBox.querySelector('.todo-archive-pop-head')){const h=document.createElement('div');h.className='todo-archive-pop-head';h.innerHTML='<div><strong>收好的胶带</strong><small>PAST DAYS</small></div>';archiveBox.insertBefore(h,archiveBox.firstChild)}archiveBox.setAttribute('aria-hidden','true');
if(authorBtn)authorBtn.remove();if(addBtn){addBtn.setAttribute('aria-label','贴上待办');addBtn.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 6 6 6-6 6"></path></svg>'}addBox.setAttribute('aria-hidden','true');addInput.placeholder='写一条今天要做的事…';
if(!addFab){addFab=document.createElement('button');addFab.type='button';addFab.id='todoFabAdd';addFab.className='todo-fab-add';addFab.setAttribute('aria-label','新增待办');addFab.setAttribute('aria-expanded','false');addFab.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path id="todoAddMorphPath" d="M12 5v14M5 12h14"></path></svg>';sheet.appendChild(addFab);addFab.onclick=e=>{e.stopPropagation();setAddOpen(!addBox.classList.contains('open'))}}
}
function setArchiveOpen(open){if(open)setAddOpen(false);archiveBox.classList.toggle('open',open);archiveBox.setAttribute('aria-hidden',open?'false':'true');archiveBtn?.setAttribute('aria-expanded',open?'true':'false');window.__todoArchiveMorph?.(open);if(open)renderArchive()}
function setAddOpen(open){if(open)setArchiveOpen(false);addBox.classList.toggle('open',open);addBox.setAttribute('aria-hidden',open?'false':'true');addFab?.setAttribute('aria-expanded',open?'true':'false');window.__todoAddMorph?.(open);if(open)setTimeout(()=>addInput?.focus({preventScroll:true}),180)}
function openSheet(){prepareToday();renderAll();if(document.querySelector('.drawer-layer.open'))document.querySelector('#drawerDim')?.click();requestAnimationFrame(()=>{layer.classList.add('open');layer.setAttribute('aria-hidden','false');document.body.classList.add('todo-sheet-open')})}
function closeSheet(){setArchiveOpen(false);setAddOpen(false);layer.classList.remove('open');layer.setAttribute('aria-hidden','true');document.body.classList.remove('todo-sheet-open');sheet.style.transform='';dragging=false;dragY=0}
function addTask(){const text=(addInput.value||'').trim();if(!text)return;const items=getToday(),id=`todo-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;items.push({id,text,done:false,creator:'小漾',completedAt:null,colorIndex:Math.floor(Math.random()*PALETTE.length)});saveToday(items);addInput.value='';renderAll();setAddOpen(false);requestAnimationFrame(()=>{const sc=$('.todo-tape-scroll');if(sc)sc.scrollTo({top:sc.scrollHeight,behavior:'smooth'})})}
ensureUi();prepareToday();renderSidebar();
drawerTodo.addEventListener('click',e=>{if(e.target.closest('.todo-item'))return;openSheet()});drawerTodoList.addEventListener('click',e=>{const item=e.target.closest('.todo-item');if(!item)return;e.preventDefault();e.stopPropagation();toggleTask(item.dataset.todoId)},true);
backdrop?.addEventListener('click',closeSheet);closeBtn?.addEventListener('click',closeSheet);addBtn?.addEventListener('click',e=>{e.stopPropagation();addTask()});addInput?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addTask()}});addBox?.addEventListener('click',e=>e.stopPropagation());archiveBox?.addEventListener('click',e=>e.stopPropagation());
sheet.addEventListener('click',e=>{if(addBox.classList.contains('open')&&!e.target.closest('.todo-add')&&!e.target.closest('.todo-fab-add'))setAddOpen(false);if(archiveBox.classList.contains('open')&&!e.target.closest('.todo-archive')&&!e.target.closest('#todoArchiveBtn'))setArchiveOpen(false)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&layer.classList.contains('open')){if(addBox.classList.contains('open'))setAddOpen(false);else if(archiveBox.classList.contains('open'))setArchiveOpen(false);else closeSheet()}});
handle?.addEventListener('pointerdown',e=>{dragging=true;dragY=e.clientY;handle.setPointerCapture?.(e.pointerId);sheet.style.transition='none'});handle?.addEventListener('pointermove',e=>{if(!dragging)return;const dy=Math.max(0,e.clientY-dragY);sheet.style.transform=`translateY(${dy}px)`});handle?.addEventListener('pointerup',e=>{if(!dragging)return;const dy=Math.max(0,e.clientY-dragY);dragging=false;sheet.style.transition='';if(dy>82)closeSheet();else sheet.style.transform=''});
window.addEventListener('storage',e=>{if(e.key===STORE||e.key===ARCHIVE_STORE)renderAll()});setInterval(()=>{if(dayKey()!==lastDay)renderAll()},60000);
(async()=>{try{const [{createMorph},{Archive,X,Plus}]=await Promise.all([import('https://esm.sh/morphicons@1.5.0/dom'),import('https://esm.sh/lucide@1.28.0')]);const archivePath=document.getElementById('todoArchiveMorphPath'),addPath=document.getElementById('todoAddMorphPath');if(archivePath){const m=createMorph(archivePath,Archive,{reducedMotion:'user'});window.__todoArchiveMorph=o=>m.morphTo(o?X:Archive,'smooth')}if(addPath){const m=createMorph(addPath,Plus,{reducedMotion:'user'});window.__todoAddMorph=o=>m.morphTo(o?X:Plus,'smooth')}}catch(err){console.warn('Todo morphicons fallback:',err)}})();
})();
