(()=>{
const STORE='chaosheng-drawer-todos-v1',ARCHIVE_STORE='chaosheng-todo-archive-v2';
const PALETTE=['#f3c9d2','#efd99b','#c7dfca','#c9dced','#d9cbe8','#efcfb6','#cbe3dc','#ead7cc'];
const $=s=>document.querySelector(s),pad=n=>String(n).padStart(2,'0');
const layer=$('#todoSheetLayer'),sheet=$('#todoSheet'),backdrop=$('#todoSheetBackdrop'),closeBtn=$('#todoSheetClose'),handle=$('#todoHandle'),drawerTodo=$('.drawer-todo'),drawerTodoList=$('#drawerTodoList');
const tapeList=$('#todoTapeList'),progressBar=$('#todoProgressBar'),progressCopy=$('#todoProgressCopy'),sheetDate=$('#todoSheetDate'),addInput=$('#todoAddInput'),authorBtn=$('#todoAuthorBtn'),addBtn=$('#todoAddBtn'),archiveBox=$('#todoArchive'),archiveToggle=$('#todoArchiveToggle'),archiveInner=$('#todoArchiveInner'),archiveCount=$('#todoArchiveCount');
if(!layer||!sheet||!drawerTodo||!drawerTodoList)return;
let author='小漾',paintId=null,dragY=0,dragging=false;
function readStore(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')||{}}catch(e){return {}}}
function writeStore(v){localStorage.setItem(STORE,JSON.stringify(v))}
function readArchive(){try{const v=JSON.parse(localStorage.getItem(ARCHIVE_STORE)||'[]');return Array.isArray(v)?v:[]}catch(e){return []}}
function writeArchive(v){localStorage.setItem(ARCHIVE_STORE,JSON.stringify(v))}
function dayKey(d=new Date()){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function prettyDate(d=new Date()){const w=['SUN','MON','TUE','WED','THU','FRI','SAT'][d.getDay()],m=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'][d.getMonth()];return `${w} · ${m} ${pad(d.getDate())}`}
function hash(s=''){let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return h}
function localTime(iso){if(!iso)return '';const d=new Date(iso);return `${pad(d.getHours())}:${pad(d.getMinutes())}`}
function defaults(){return [{id:'water',text:'今天喝水',done:false,creator:'小漾'},{id:'parcel',text:'下午拿快递',done:false,creator:'小漾'}]}
function normalizeTask(t,i,date){const id=t.id||`todo-${date}-${i}-${Date.now()}`;return {id,text:String(t.text||'待办'),done:!!t.done,creator:t.creator||'小漾',completedAt:t.completedAt||null,colorIndex:Number.isInteger(t.colorIndex)?t.colorIndex:hash(id)%PALETTE.length}}
function prepareToday(){const today=dayKey(),store=readStore(),archive=readArchive();let changed=false,archiveChanged=false;
const keys=Object.keys(store).filter(k=>/^\d{4}-\d{2}-\d{2}$/.test(k)).sort();
for(const k of keys){if(k>=today)continue;const items=(store[k]||[]).map((t,i)=>normalizeTask(t,i,k));store[k]=items;for(const t of items){if(!t.done)continue;const akey=`${k}:${t.id}`;if(archive.some(a=>a.key===akey))continue;archive.push({key:akey,date:k,id:t.id,text:t.text,creator:t.creator||'小漾',completedAt:t.completedAt||`${k}T23:59:00`,colorIndex:t.colorIndex});archiveChanged=true}}
if(!store[today]){const prev=keys.filter(k=>k<today).pop(),source=prev?(store[prev]||[]):defaults();store[today]=source.map((t,i)=>{const n=normalizeTask(t,i,today);return {...n,done:false,completedAt:null}});changed=true}else{store[today]=store[today].map((t,i)=>normalizeTask(t,i,today));changed=true}
if(changed)writeStore(store);if(archiveChanged)writeArchive(archive);return store[today]}
function getToday(){const store=readStore(),today=dayKey();return (store[today]||prepareToday()).map((t,i)=>normalizeTask(t,i,today))}
function saveToday(items){const store=readStore();store[dayKey()]=items;writeStore(store)}
function tapeColor(t){return PALETTE[(t.colorIndex||0)%PALETTE.length]}
function toggleTask(id){const items=getToday(),item=items.find(x=>x.id===id);if(!item)return;item.done=!item.done;if(item.done){item.completedAt=new Date().toISOString();paintId=id}else{item.completedAt=null;paintId=null}saveToday(items);renderAll()}
function renderSidebar(){const items=getToday();drawerTodoList.innerHTML='';items.slice(0,3).forEach(item=>{const b=document.createElement('button');b.type='button';b.className='todo-item'+(item.done?' done':'');b.dataset.todoId=item.id;b.innerHTML='<span class="todo-box"></span><span class="todo-text"></span>';b.querySelector('.todo-box').textContent=item.done?'✓':'';b.querySelector('.todo-text').textContent=item.text;drawerTodoList.appendChild(b)});if(items.length>3){const more=document.createElement('div');more.className='todo-more-count';more.textContent=`+ ${items.length-3} MORE`;drawerTodoList.appendChild(more)}}
function renderSheet(){const items=getToday(),done=items.filter(x=>x.done).length,total=items.length;sheetDate.textContent=prettyDate();progressBar.style.width=total?`${done/total*100}%`:'0%';progressCopy.textContent=`${done} / ${total} 彩色了`;tapeList.innerHTML='';if(!items.length){tapeList.innerHTML='<div class="todo-tape-empty">今天还没有贴上任何胶带。</div>'}items.forEach(item=>{const b=document.createElement('button');b.type='button';b.className='todo-tape'+(item.done?' done':'')+(paintId===item.id?' just-painted':'');b.dataset.todoId=item.id;b.style.setProperty('--tape-color',tapeColor(item));b.innerHTML=`<div class="tape-main"><span class="tape-check">${item.done?'✓':''}</span><span class="tape-text"></span></div><div class="tape-meta"><span class="tape-author"></span><span class="tape-time"></span></div>`;b.querySelector('.tape-text').textContent=item.text;b.querySelector('.tape-author').textContent=`${item.creator||'小漾'} added`;b.querySelector('.tape-time').textContent=item.done?`${localTime(item.completedAt)} done`:'waiting';b.onclick=()=>toggleTask(item.id);tapeList.appendChild(b)});setTimeout(()=>paintId=null,900);renderArchive()}
function renderArchive(){const archive=readArchive().sort((a,b)=>(b.date+b.completedAt).localeCompare(a.date+a.completedAt));archiveCount.textContent=archive.length;archiveInner.innerHTML='';archive.slice(0,18).forEach(a=>{const d=document.createElement('div');d.className='archive-strip';d.style.setProperty('--archive-color',PALETTE[(a.colorIndex||0)%PALETTE.length]);d.innerHTML='<span></span><small></small>';d.querySelector('span').textContent=a.text;d.querySelector('small').textContent=`${a.date.slice(5).replace('-','.')} · ${localTime(a.completedAt)}`;archiveInner.appendChild(d)});if(!archive.length){archiveInner.innerHTML='<div class="todo-tape-empty" style="padding:10px 4px">还没有收进盒子的旧胶带。</div>'}}
function renderAll(){prepareToday();renderSidebar();renderSheet()}
function openSheet(){prepareToday();renderAll();if(document.querySelector('.drawer-layer.open'))document.querySelector('#drawerDim')?.click();requestAnimationFrame(()=>{layer.classList.add('open');layer.setAttribute('aria-hidden','false');document.body.classList.add('todo-sheet-open');addInput?.focus({preventScroll:true})})}
function closeSheet(){layer.classList.remove('open');layer.setAttribute('aria-hidden','true');document.body.classList.remove('todo-sheet-open');sheet.style.transform='';dragging=false;dragY=0}
function addTask(){const text=(addInput.value||'').trim();if(!text)return;const items=getToday(),id=`todo-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;items.push({id,text,done:false,creator:author,completedAt:null,colorIndex:hash(id)%PALETTE.length});saveToday(items);addInput.value='';renderAll();requestAnimationFrame(()=>{const sc=$('.todo-tape-scroll');if(sc)sc.scrollTo({top:sc.scrollHeight,behavior:'smooth'})})}
prepareToday();renderSidebar();
drawerTodo.addEventListener('click',e=>{if(e.target.closest('.todo-item'))return;openSheet()});
drawerTodoList.addEventListener('click',e=>{const item=e.target.closest('.todo-item');if(!item)return;e.preventDefault();e.stopPropagation();toggleTask(item.dataset.todoId)},true);
backdrop?.addEventListener('click',closeSheet);closeBtn?.addEventListener('click',closeSheet);addBtn?.addEventListener('click',addTask);addInput?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addTask()}});authorBtn?.addEventListener('click',()=>{author=author==='小漾'?'声声':'小漾';authorBtn.textContent=author;authorBtn.classList.toggle('sheng',author==='声声')});archiveToggle?.addEventListener('click',()=>{const open=archiveBox.classList.toggle('open');archiveToggle.setAttribute('aria-expanded',open?'true':'false')});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&layer.classList.contains('open'))closeSheet()});
handle?.addEventListener('pointerdown',e=>{dragging=true;dragY=e.clientY;handle.setPointerCapture?.(e.pointerId);sheet.style.transition='none'});handle?.addEventListener('pointermove',e=>{if(!dragging)return;const dy=Math.max(0,e.clientY-dragY);sheet.style.transform=`translateY(${dy}px)`});handle?.addEventListener('pointerup',e=>{if(!dragging)return;const dy=Math.max(0,e.clientY-dragY);dragging=false;sheet.style.transition='';if(dy>82)closeSheet();else sheet.style.transform=''});
window.addEventListener('storage',e=>{if(e.key===STORE||e.key===ARCHIVE_STORE)renderAll()});
})();
